### ISSUE TITLE
Igir improvement for Tosec new gameType

### ISSUE THREAD

**Issue by MrNoOneRed** [emmercm/igir#1071]
### Is your feature request related to a problem?

Igir do not recognize tosec's dump flag [cr]

### Describe the solution you'd like

It could be greate if igir could separate roms with [cr] flag as {gameType} Cracked or similiar like Pirate, Hacked etc.

### Additional context

Thanks for Igir, best rom manager in the universe :)

**Comment by emmercm** [comment]
I think this is a good suggestion. I also think these releases should _not_ be treated as "retail".
