### ISSUE TITLE
failed to run command

### ISSUE THREAD

**Issue by allengray69** [emmercm/igir#1084]
### Paste the command

running igir, even without parms...

2024/04/11 19:02:21 caxa stub: Failed to run command: exec: "C:\\Users\\Administrator\\AppData\\Local\\Temp/caxa/applications/igir\\icrkn08po1/0/node_modules/.bin/node": file does not exist

i had this error with the version before the last one too

windows 11 pro
windows server 2025

### Describe the bug

2024/04/11 19:02:21 caxa stub: Failed to run command: exec: "C:\\Users\\Administrator\\AppData\\Local\\Temp/caxa/applications/igir\\icrkn08po1/0/node_modules/.bin/node": file does not exist

### Expected behavior

expect it to work

### Debug logs

it won't run to get any logs.

### igir version

2.62

### Node.js version

n/a

### Operating system

windows 11 pro and windows server 2025

### Additional context

%temp%=igir, caxa

deleted %temp% does nothing

**Comment by emmercm** [comment]
Does any bundled version of `igir.exe` work for you, or just v2.6.2 and v2.6.1?

After running `igir.exe`, can you list the contents of these directories:

- `C:\Users\Administrator\AppData\Local\Temp/caxa/applications/igir\icrkn08po1/0/node_modules/.bin`
- `C:\Users\Administrator\AppData\Local\Temp\caxa\applications\igir\icrkn08po1\0\node_modules\@node-rs`
- `C:\Users\Administrator\AppData\Local\Temp\caxa\applications\igir\icrkn08po1\0\node_modules\@node-rs\crc32-win32-x64-msvc`
