### ISSUE TITLE
Hashes are case sensitive

### ISSUE THREAD

**Issue by knoopx** [emmercm/igir#1144]
### Paste the command

igir copy zip --dat dat_with_uppercase_checksums.dat

### Describe the bug

igir was parsing the roms but not actually outputting anything, turns out hashes in the dats were uppercased. once i turned them lowercase they were copied to the output dir.

### Expected behavior

hashes should not be case-sensitive

### Debug logs

-

### igir version

v2.7.0

### Node.js version

-

### Operating system

-

**Comment by emmercm** [comment]
Definitely a bug, likely a regression from some point. I'll fix.
