### ISSUE TITLE
Prevent file name collision

### ISSUE THREAD

**Issue by Djabal** [emmercm/igir#1201]
### Is your feature request related to a problem?

Do not write the same file twice in one copy/move/zip/whatever.

Two use case :

- Some dats (like this one : https://datomatic.no-intro.org/index.php?page=download&op=dat&s=140) list different game version with the same physical name.  
- When you use multiple dat from different sources at the same time some game can have the same physical name.

### Describe the solution you'd like

Igir could write a warning when it detect that it gonna overwrite a file he wrote in the same run, and of course don't overwrite. 
"The name file "maria.rom" seems to be used by two games [put here games details for identification]. Currently the file "maria.rom" contains the game [the game detail]."

**Comment by emmercm** [comment]
Can you tell me more about your specific use case?

It generally does _not_ make sense to have two DATs write their files to the same directory. That's why the various [`--dir-dat-*` options](https://igir.io/output/path-options/#append-dat-name) exist. And DATs don't (or shouldn't) have files of the same name with different checksums.

**Comment by Djabal** [comment]
I was importing ps3 bios in my bios folder, igir said it has found and write 3 bioses. But when I ask a report on the bios folder it had only 1 bios. Take me some time to understand where was the problem. 
	
```
<game name="[BIOS] PS3 System Software Update (World) (v4.88)" id="12137">
  <description>[BIOS] PS3 System Software Update (World) (v4.88)</description>
  <rom name="PS3UPDAT.PUP" size="206146716" crc="9d98af0b" md5="a0b63a3e4ae92ed176d6b9a67ce447f0" [...]>
</game>
<game name="[BIOS] PS3 System Software Update (World) (v4.89)" id="12138">
  <description>[BIOS] PS3 System Software Update (World) (v4.89)</description>
  <rom name="PS3UPDAT.PUP" size="206197040" crc="29705956" md5="95307e1b51d3bcc33a274db91488d29f" [...]/>
</game>
```
If Igir had warn me it was rewriting 3 times the same filename I'll have understood faster.

Maybe you're right about having two DATs write their files to the same directory, I dun know !

Ty,

**Comment by emmercm** [comment]
Every time I think I know what the standards of various DAT groups are, they surprise me 🙂.

I'll think about how I want to handle a conflict warning/error, I think it's a good suggestion.

In the meantime, I'll fix up parent/clone inference for this so you can use `--single --prefer-revision-newer` or other 1G1R options.

**Comment by Djabal** [comment]
Thanks !
