### ISSUE TITLE
Cache more stuff

### ISSUE THREAD

**Issue by dch82** [emmercm/igir#1234]
### Is your feature request related to a problem?

I think it would speed things up a _lot_ more if stuff like header detection and DAT detection was cached because right now a lot of these high quantity operations take a lot of time.

### Describe the solution you'd like

To cache results of operations so they take less time after the first run.

**Comment by emmercm** [comment]
I fully agree on header detection, it's something I've been thinking about recently. The recent extension correction features fall into this same bucket as well. And I think it will be even more important as I'm adding support for compressed disc images such as CHD and NKit.

Can you elaborate more on the "DAT detection" piece?

**Comment by dch82** [comment]
Like when IGIR reads the files and makes sure they are valid dats

**Comment by emmercm** [comment]
Scanning for + parsing the contents of DATs is generally fast unless processing an exceptionally large archive such as TOSEC's. Loading it from a cache file would take roughly the same amount of time, except it would greatly increase the cache file's size.

I'll look to focus on the other features soon.
