### ISSUE TITLE
Add an option for a list file with games to export/copy. 

### ISSUE THREAD

**Issue by dmitriibaboshin** [emmercm/igir#1241]
### Is your feature request related to a problem?

Your app is awesome. Thank you so much.  

I formed my games repository with DATs using it. Realy like that such a tool now exists.  

### Feature Request. 

I don't want to export all games into sd card for mister or other emulators. In most cases i want a list file to be checked against and copy only some games written in this list file.  

### Describe the solution you'd like

1. Generate a report in .json format (csv is already supported now)  

2. Add parameter like --games-whitelist where i can add edited json from report with limited game set to export/copy only them, not all games.  

Therefore i will be able to make many json lists for games exports for different devices. Not all of devices have memory for a full games repo export/copy.

**Comment by emmercm** [comment]
Hi @dmitriibaboshin, I believe the `--filter-regex <filename>` option is what you're looking for. It allows for providing a file of regex patterns to match against game names, one pattern per line, with the results of those checks logically ORed together. This behavior is documented at https://igir.io/roms/filtering-preferences/#game-name-filter.

**Comment by dmitriibaboshin** [comment]
Oh. Sorry, somehow i missed this. Thank you! I'll try!

**Comment by dmitriibaboshin** [comment]
Works with some game name tweaks for regex. 🙂
