### ISSUE TITLE
Add the ability to exclude duplicate games from multi-regions

### ISSUE THREAD

**Issue by avelytchko** [emmercm/igir#1339]
### Is your feature request related to a problem?

Some games were released simultaneously in all regions, while others were only released in a specific one. If there is a duplicate of a game across multiple regions, I can successfully exclude it using the --filter-region key, for example, USA. However, in such a case, games that were only released in EUR will also be excluded. I would like to have the ability to exclude duplicate games if they were released for multiple regions at once, without removing games that were released for just one region.

```
-rw-rw-r-- 1 rand rand  257884 Sep  5 09:21 Arrow Flash (USA).zip
-rw-rw-r-- 1 rand rand   58851 Sep  5 09:21 Art Alive (World).zip
-rw-rw-r-- 1 rand rand  951495 Sep  5 09:21 Art of Fighting (Europe).zip
-rw-rw-r-- 1 rand rand  953420 Sep  5 09:21 Art of Fighting (USA).zip
-rw-rw-r-- 1 rand rand 1300223 Sep  5 09:21 ClayFighter (Europe).zip
-rw-rw-r-- 1 rand rand 1300220 Sep  5 09:21 ClayFighter (USA).zip
-rw-rw-r-- 1 rand rand  547244 Sep  5 09:21 Cliffhanger (Europe).zip
-rw-rw-r-- 1 rand rand  549169 Sep  5 09:21 Cliffhanger (USA).zip
```
For the case mentioned above, here's an example -

`npx igir@latest copy --input /md-orig/ --output /md-sort/ --overwrite --filter-region EUR,WORLD,USA --no-unlicensed --only-retail --filter-language EN --remove-duplicates --duplicates-prefer-region USA`

If there are duplicate games from different regions, only those in the USA region will be copied.

### Describe the solution you'd like

In the case where the same game was released in a multi-region, only one region will be copied. Single-region games will not be affected and will be copied also.

**Comment by Djabal** [comment]
Hi @avelytchko,
To achieve your goal, you can use the --single option associated the options --prefer-region USA and --prefer-language EN.
You need to use a dat with the --dat option.
`igir copy --input /md-orig/ --output /md-sort/ --overwrite --filter-region EUR,WORLD,USA --no-unlicensed --only-retail --single --prefer-region USA --prefer-language EN --dat md.dat`

**Comment by avelytchko** [comment]
Hi @Djabal . Thank you! I've realized that 1G1R already implemented via --single.

**Comment by emmercm** [comment]
@Djabal is right here, you want the `--single` option for 1G1R functionality like this. There are several [preference options](https://igir.io/roms/filtering-preferences/#preferences-for-1g1r) that you can combine, in case language or region isn't specific enough.
