### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by Europia79** [emmercm/igir#1343]
### Paste the command

`igir.exe --help`
`npx igir@latest --help`

### Describe the bug

...with the executable release (for Windows x64), **igir** does nothing at all.

...trying with **npx**, it throws an Exception & stack trace:

```
D:\Users\Euro\igir\v3.0.0>npx igir@latest --help
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by
 the default ESM loader
←[90m    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js
:669:11)←[39m
←[90m    at Loader.resolve (internal/modules/esm/loader.js:97:40)←[39m
←[90m    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)←[39m
←[90m    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)←[3
9m
←[90m    at link (internal/modules/esm/module_job.js:41:36)←[39m {
  code: ←[32m'ERR_UNSUPPORTED_ESM_URL_SCHEME'←[39m
}

D:\Users\Euro\igir\v3.0.0>

```

### Expected behavior

display help

### Debug logs

N/A (cannot get **igir** to run).

### DAT(s) used

N/A

### igir version

v3.0.0 / v2.11.0 / v2.10.1 / v2.10.0

### Node.js version

v13.14.0

### Operating system

Windows 7 Professional 64-bit Version 6.1 (Build 7601: Service Pack 1)

### Additional context

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

D:\Users\Euro>cd igir

D:\Users\Euro\igir>dir
 Volume in drive D has no label.
 Volume Serial Number is 6C38-E086

 Directory of D:\Users\Euro\igir

09/15/2024  04:34 PM    <DIR>          .
09/15/2024  04:34 PM    <DIR>          ..
09/15/2024  02:42 PM    <DIR>          roms
09/15/2024  04:33 PM    <DIR>          v2.10.0
09/15/2024  04:34 PM    <DIR>          v2.10.1
09/15/2024  04:30 PM    <DIR>          v2.11.0
09/15/2024  04:30 PM    <DIR>          v3.0.0
               0 File(s)              0 bytes
               7 Dir(s)  1,375,202,533,376 bytes free

D:\Users\Euro\igir>cd v3.0.0

D:\Users\Euro\igir\v3.0.0>igir.exe --help

D:\Users\Euro\igir\v3.0.0>node --version
v13.14.0

D:\Users\Euro\igir\v3.0.0>npx --version
6.14.4

D:\Users\Euro\igir\v3.0.0>npx igir@latest --help
internal/modules/run_main.js:54
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by
 the default ESM loader
←[90m    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js
:669:11)←[39m
←[90m    at Loader.resolve (internal/modules/esm/loader.js:97:40)←[39m
←[90m    at Loader.getModuleJob (internal/modules/esm/loader.js:243:28)←[39m
←[90m    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)←[3
9m
←[90m    at link (internal/modules/esm/module_job.js:41:36)←[39m {
  code: ←[32m'ERR_UNSUPPORTED_ESM_URL_SCHEME'←[39m
}

D:\Users\Euro\igir\v3.0.0>
```
![image](https://github.com/user-attachments/assets/d0ce6dd1-eb13-49b0-9722-012142ca27a2)

**Comment by Europia79** [comment]
heya @emmercm  !!!

i don't really think we should spend too much time on this "issue" seeing how old **Windows 7** is.

Mainly, i just wanted to add **igir** support to my own tools (an alternative autopatcher implementation for romhacks & translations).  I have already added support for **ucon64** and **SabreTools**:

So, to add **igir** support, I would just need two commands (and their resulting behaviors):  1st, for creating dat files.  And 2nd, for using that dat to rename ROMs.

For creating DATs, it appears to be
```
igir dir2dat --input "roms"
```
And the results appears to be `roms (20240915-141555).dat` ?
...is that DAT saved in the **igir** folder ?
...or is it saved where the command is executed ?

But what is the command to use that DAT to rename files ?  ...TY !!!

**Comment by emmercm** [comment]
Unfortunately, I don't have a Windows 7 machine to debug the executable. If you increase the log verbosity with `-vvv` do you get any output?

For your npx command, Igir only supports Node.js >=16.7.0 per [package.json](https://github.com/emmercm/igir/blob/990fdcd938d1a48b3bde576693ec8f07ef2897ee/package.json#L154). Windows 7 should be supported as long as you can install a newer version of Node.js.

Please separate the `dir2dat` question into a different issue or discussion.

**Comment by Europia79** [comment]
still no output at all from the executable with the `-vvv` option.

And **Node16** requires **Windows 8** or higher:

![image](https://github.com/user-attachments/assets/a273e24c-f38b-405e-a1ab-fc999d02e478)

i think the only alternatives here would be for me to either (1) rebuild **igir** against **Node** 12 or 13, or (2) download the source for **Node** 16-22 and build against **Windows 7** ?  lol

But I'm not familiar with the **Node** ecosystem at all, so not sure about option one.
Option two is probably more "doable" (altho, time consuming).

Alternatively, I could simply do a VM or VPS.

Right now, my **Windows 10** VM has a virus & runs excruciatingly slow (like a drunk Turtle).

So, probably my best option would be a **Linux** VM or VPS ?

**Comment by IDmedia** [comment]
Support for Windows 7 ended on January 14, 2020!

Just make a new Windows or Linux VM... or run it directly in Docker...

Example dockerfile:
```
# Use the official Node.js image
FROM node:latest

# Set the working directory inside the container
WORKDIR /roms

# Define environment variables
ENV DAT_DIR=./dats
ENV IMPORT_DIR=./import
ENV OUTPUT_DIR=./output/roms
ENV CLEAN_BACKUP_DIR=./trash
ENV REPORT_FILE=report.csv

# Process roms
CMD ["sh", "-c", "\
    npx igir@latest move zip test clean report \
    --dat $DAT_DIR \
    --input $IMPORT_DIR \
    --input $OUTPUT_DIR \
    --output $OUTPUT_DIR/{datName} \
    --clean-backup $CLEAN_BACKUP_DIR \
    --single \
    --only-retail \
    --no-unlicensed \
    --no-bios \
    --prefer-revision newer \
    --prefer-region USA,WORLD,EUR,JPN \
    --report-output $OUTPUT_DIR/$REPORT_FILE \
"]
```

Build it:
`docker build -t igir:latest .`

Run it:
`docker run -it --rm -v /mnt/user/roms:/roms igir:latest`


This issue should be closed in my opinion.

**Comment by emmercm** [comment]
> rebuild igir against Node 12 or 13

Igir is using language features that make this impossible.

> Alternatively, I could simply do a VM or VPS.

You should be able to use Docker on your Windows 7 machine like @IDmedia to do this. I used to have instructions in the documentation but removed them [here](https://github.com/emmercm/igir/pull/1245/files#diff-8b042e3f94ca5c59a7cd990b950aec0073ea84fe811e7b22be51158d7b180d56). You won't need to make a `Dockerfile`, you can use the official Node.js image.

**Comment by Europia79** [comment]
@IDmedia  @emmercm 

Thanks for helping !!!

Looks like Docker only supports Windows 10 & 11 now:  ...So i will have to install a new VM.

But what is this "200 image pulls per 6 hours" on their Free Plan ?
...is that a limitation that i need to plan around ?

![image](https://github.com/user-attachments/assets/4cce3308-1f09-4b54-98c6-f7fd78d3cfb8)

**Comment by IDmedia** [comment]
You don't have to worry about the pull limit at all.

You have to upgrade no matter what. As mentioned before, Windows 7 is old and unsupported. There's absolutely no reason to continue using it.

**Comment by emmercm** [comment]
Agreed you don't need to worry about the Docker Hub license limitations. You can sign up for a free account and it will let you have some more bandwidth.

There are likely older versions of Docker Desktop you can find for Windows 7, but I would be wary of sketchy download sites.

A VM should work if you're truly stuck on Windows 7, but I wouldn't be surprised if VM software is also not supporting Windows 7 anymore.
