### ISSUE TITLE
Question how to bulk patch

### ISSUE THREAD

**Issue by coolfox89** [emmercm/igir#1345]
### Is your feature request related to a problem?

I need help with bulk patching. I’m a beginner with scripts and code so I’m not sure how to apply this.

### Describe the solution you'd like

I would like to bulk patch the Romhacking.net archive since its recent shutdown. How do I use your tool to bulk patch? Can you send me an example of what a bulk patch would look like?

The Romhacking.net archive has a SQL file that contains hash values for the patches. Would your tool be able to work with the SQL file to help automate the patching process?

**Comment by emmercm** [comment]
I'm going to convert this to a discussion as it's not a feature, but I do think it's a really interesting discussion.
