### ISSUE TITLE
Add a --dat-exclude path option

### ISSUE THREAD

**Issue by chainsawsalad** [emmercm/igir#282]
### Is your feature request related to a problem?

No-Intro's DAT-o-Matic site provides a way of downloading a full zipped archive of all DATs via the `daily` filter. It would be convenient to run igir using this archive, but to have the option to "exclude DAT" to avoid unneeded scans or erroneous matching, for example in situations where games appear in both `Nintendo - Nintendo 64 (BigEndian)` and `Nintendo - Nintendo 64 (ByteSwapped)` DAT files, but you're only interested in maintaining a BigEndian collection.

### Describe the solution you'd like

Similar to `--input-exclude`, a flag like `--dat-exclude` that would ignore any matching DAT files.

**Comment by emmercm** [comment]
I'd probably make a `--dat-exclude` to be consistent with `--input-exclude` where it specifies files on disk - but something such as `--dat-name` (allow list regex) and `--dat-name-exclude` (disallow list regex) could make a lot of sense. Let me think on that one!

**Comment by emmercm** [comment]
It's not easy to look at the diff in #283, so would this fit your needs:

```text
DAT input options:
  -d, --dat                Path(s) to DAT files or archives (supports globbing)                        [array]
      --dat-exclude        Path(s) to DAT files or archives to exclude from processing (supports globbing)
                                                                                                       [array]
      --dat-regex          Regular expression of DAT names to process (case-insensitive)              [string]
      --dat-regex-exclude  Regular expression of DAT names to exclude from processing (case-insensitive)
                                                                                                      [string]
```

as in:

```shell
igir copy \
  --dat "No-Intro*.zip" --dat-regex-exclude "ByteSwapped" \
  --input ROMs/ --output ROMs-Filtered/
```

**Comment by chainsawsalad** [comment]
Yes, this would definitely solve my use case!
