### ISSUE TITLE
Non-existing `--clean-exclude` file/folder throws error and stops `igir` command

### ISSUE THREAD

**Issue by fooness** [emmercm/igir#319]
When running `igir` as in your documented [`igir_pocket_sync.sh`](https://github.com/emmercm/igir/blob/main/docs/advanced-examples.md#analogue-pocket) script, with some path or glob to be excluded like for example `--clean-exclude "./Assets/*/common/*.*"`, the command/script currently throws an error and stops if the path or glob to be excluded does not exist, i.e. nothing matches the exclude path or glob.

Thinking about this behavior, I’d say it would make more sense to be able to define whatever exludes as one wishes, and if something matches, it get’s excluded as defined, and if nothing matches, i.e. nothing exists that matches, the command/script should gracefully continue and finish.

I’m not sure if this only is the case for `--clean-exclude` or also some of the other `--*-exclude` flags.

**Comment by emmercm** [comment]
Great suggestion, I agree this should not be a fatal error.

The file scanning for `--input`, `--dat`, `--patch`, and `--clean-exclude` all go through the same code path, but they shouldn't be treated with the same importance.
