### ISSUE TITLE
Specify recursion depth

### ISSUE THREAD

**Issue by milnak** [emmercm/igir#358]
### Describe the solution you'd like

I have a folder like `ROMS\ARCADE\Imgs`, `ROMS\ATARI\Imgs`  I want to include ARCADE and ATARI (first level) but nothing below that.  I can specify all possible ROM extensions (zip, 7z, etc. ) with multiple --input but that's a bit awkward

**Comment by emmercm** [comment]
You can use file globbing like this:

```
--input "ROMS/{ARCADE,ATARI}/Imgs/*"
```

https://globster.xyz/?q=ROMS%2F%7BARCADE%2CATARI%7D%2FImgs%2F*&f=ROMS%2FARCADE%2FImgs%2FOne.rom%2CROMS%2FARCADE%2FImgs%2FDir%2FTwo.rom%2CROMS%2FATARI%2FImgs%2FThree.rom%2CROMS%2FATARI%2FImgs%2FDir%2FFour.rom%2CROMS%2FELSE%2FImgs%2FFive.rom%2CROMS%2FELSE%2FImgs%2FDir%2FSix.rom

I'll keep this issue open to write some docs on file input and output.
