### ISSUE TITLE
Add fixdat support

### ISSUE THREAD

**Issue by graphixillusion** [emmercm/igir#364]
### Is your feature request related to a problem?

This feature allows the creation of a fixdat with all the entries which are missing from the main dat, so it will be easy to search and rebuild the missing roms

### Describe the solution you'd like

a flag to the command "report" for example something like "--fix-dat" which creates the dat with only the missing entries of the main dat.

### Additional context

example of a fixdat content created with RomVault:

```
<?xml version="1.0"?>
<datafile>
	<header>
		<name>FixDat_datname</name>
		<description>FixDat_datname</description>
		<version>20230412-000000</version>
		<date>2023-04-12</date>
		<author>RomVault</author>
		<homepage>N/A</homepage>
		<url>N/A</url>
		<romvault/>
	</header>
	<game name="gamename">
		<description>gamename</description>
		<rom name="romname" size="1048576" crc="crc32" md5="md5"/>
	</game>
</datafile>
```

**Comment by graphixillusion** [comment]
Thank you very much for this addition!

**Comment by emmercm** [comment]
You're very welcome!
