### ISSUE TITLE
Don't delete moved archives unless every entry was matched

### ISSUE THREAD

**Issue by veraciousnottaken** [emmercm/igir#376]
### Paste the command

`igir move zip test report --input atari-test --output No-Intro-Atari --overwrite --dir-dat-name --single --dat Atari.zip`

### Describe the bug

I don't know if it's a bug or how it's supposed to work, but to clear the source directory of files, I have to repeat the `igir move` command three times (in this case, on this set of files).

For example:
```
Test conditions:
	Input directory files: 602
	Output directory files: 0
	No txt, images, etc

First run:
	√ Scanning for DATs ············ | 3 unique DATs found
	√ Scanning for ROMs ············ | 506 unique ROMs found
	√ Detecting ROM headers ········ | 506 ROMs processed
	√ Atari - 7800 ················· | 0/2 BIOSes, 58/112 retail releases written
	√ Atari - ST ··················· | 314/314 retail releases written
	√ Deleting moved files ········· | 485 moved files deleted
	√ Generating report ············ | .\igir_2023-04-15T12;21;55.csv
	Input directory files: 117 - OK
	Output directory files: 379
	
	
Second run:
	√ Scanning for DATs ············ | 3 unique DATs found
	√ Scanning for ROMs ············ | 60 unique ROMs found
	√ Detecting ROM headers ········ | 60 ROMs processed
	√ Atari - 7800 ················· | 0/2 BIOSes, 58/112 retail releases written
	√ Deleting moved files ········· | 60 moved files deleted
	√ Generating report ············ | .\igir_2023-04-15T12;30;11.csv
	Input directory files: 57 - OK
	Output directory files: 381
	
Third run:
	√ Scanning for DATs ············ | 3 unique DATs found
	√ Scanning for ROMs ············ | 57 unique ROMs found
	√ Detecting ROM headers ········ | 57 ROMs processed
	√ Atari - 7800 ················· | 0/2 BIOSes, 57/112 retail releases written
	√ Deleting moved files ········· | 57 moved files deleted
	√ Generating report ············ | .\igir_2023-04-15T12;41;16.csv
	Input directory files: 0 - OK
	Output directory files: 381
```

### Expected behavior

Why files aren't processed in one run?

### Debug logs

[Trace.zip](https://github.com/emmercm/igir/files/11239184/Trace.zip)

### igir version

1.6.0

### Node.js version

igir.exe

### Operating system

Windows 10

**Comment by emmercm** [comment]
Do you have duplicate ROMs in your input directory? `igir move` will only move the first file found and leave the duplicates alone.

**Comment by veraciousnottaken** [comment]
> Do you have duplicate ROMs in your input directory? `igir move` will only move the first file found and leave the duplicates alone.

Of course I have duplicates ;) ones in `.7zip` and ones in `.zip` (of the same ROM). As you can see from the above logs, after three passes, the `input` directory is empty.
And here I noticed an interesting thing. I unpacked all the files (in the atari7800 directory) and let's take for example ROM:

- F-18 Hornet.7z
- F-18 Hornet.zip
- F-18 Hornet (1988) (Absolute).zip

which gives:

- F-18 Hornet (1988) (Absolute) [!].a78
- F-18 Hornet (1988) (Absolute) [b1].a78
- F-18 Hornet (1988) (Absolute) [b2].a78
- F-18 Hornet (USA).a78
- F-18 Hornet.a78

And I repeated the `igir move zip test report --input atari-test --output No-Intro-Atari --overwrite --dir-dat-name --single --dat Atari.zip` command and the following files were left in the input directory:

- F-18 Hornet (1988) (Absolute) [b1].a78
- F-18 Hornet (1988) (Absolute) [b2].a78

Full list of files that have been left in the input directory:

- F-18 Hornet (1988) (Absolute) [b1].a78
- F-18 Hornet (1988) (Absolute) [b2].a78
- Impossible Mission (1987) (Atari) [a1].a78
- Impossible Mission (1987) (Atari) [f1].a78
- Pete Rose Baseball (1989) (Absolute) [o1].a78
- Rampage (1989) (Activision) [b1].a78
- Rampage (1989) (Activision) [b1][o1].a78
- RealSports Baseball (1988) (Atari) [o1].a78
- Super Skateboardin' (1989) (Absolute) [o1].a78
- Tank Command (1988) (Froggo) [b1].a78
- Tank Command (1988) (Froggo) [o1].a78
- Title Match Pro Wrestling (1989) (Absolute) [o1].a78
- Tower Toppler (1988) (Atari) [o1].a78
- Water Ski (1988) (Froggo) [b1].a78
- Water Ski (1988) (Froggo) [o1].a78

Why were they all removed when they were packed? Shouldn't `move` leave unfamiliar files in place?

DAT content regarding F-18:
```
<game name="F-18 Hornet (Europe)">
  <description>F-18 Hornet (Europe)</description>
  <release name="F-18 Hornet (Europe)" region="EUR"/>
  <rom name="F-18 Hornet (Europe).a78" size="65536" crc="e5d714b0" md5="e7709da8e49d3767301947a0a0b9d2e6" sha1="673d912b2f9ab7a43f95e0e90bd80249b360fe0d"/>
</game>
<game name="F-18 Hornet (USA)" cloneof="F-18 Hornet (Europe)">
  <description>F-18 Hornet (USA)</description>
  <release name="F-18 Hornet (USA)" region="USA"/>
  <rom name="F-18 Hornet (USA).a78" size="65536" crc="63d1c7c1" md5="2251a6a0f3aec84cc0aff66fc9fa91e8" sha1="13a18a6b85db6222b01d37800e5e57db616a85a6"/>
</game>
```

When ROM is extracted then it's marked as *UNMATCHED* in report and when passed as archive there's no *UNMATCHED* section at all.

**Comment by emmercm** [comment]
There are a few things to unpack here.

It's expected that input files were de-duplicated and that duplicates were left in the input directory. Only one file needed to be moved, not three. It sounds like you might want to `rm -rf` the input directory after `igir move` has finished.

---

For those `[b#]` ROMs, those are bad dumps per the [GoodTools naming convention](https://emulation.gametechwiki.com/index.php/GoodTools#Good_codes). Most release groups do not include bad dumps in their DATs. It makes sense that all of those files were left alone in your input directory, I would expect only the `[!]` files to have matched a DAT.

It is not typical that you have different ROM dumps in one archive. Other than disc-based consoles (e.g. BIN/CUE files), ROMs are typically archived individually (unless you're archiving every ROM in a DAT).

When moving files, if any files within the archive are a match, then the entire archive is considered a match and it will be deleted after writing has finished. An option could be to delete the file from the input archive and rebuild it, but `igir` only supports writing zip files on purpose, and I personally would find this behavior unexpected.

What are your thoughts?

**Comment by veraciousnottaken** [comment]
Regardless of whether I want something to stay in the directory or not, the behavior of the program is different when files are unpacked or packed and that made me wonder! 

Now I understand why:
In the archive: `F-18 Hornet (1988) (Absolute).zip` I have three files (you say it's not typical but it happened ;))

```
F-18 Hornet (1988) (Absolute) [!].a78
F-18 Hornet (1988) (Absolute) [b1].a78
F-18 Hornet (1988) (Absolute) [b2].a78
```

`igir` recognized `[!]` and decided to delete the whole `zip` file because it was processed as a whole.

Personally, I would leave the decision to the user, i.e. in practice leave the entire source file untouched and only copy the `[!]` file to the output directory. Maybe more information in the report. At the moment the file disappears and we don't really know what data we lost.

By the way, this situation can be abstract at all, because as you say, there shouldn't be several ROMs in one archive, and maybe there's no point in worrying about it.

Anyway, thank you very much for your answer and great tool :)

**Comment by emmercm** [comment]
I'll have to think through how to recognize input archives as only having partially matched - the internals of `igir` track each file within archives as an entirely separate entity.

I'll convert this over to a feature request, but thank you for working through it with me!
