### ISSUE TITLE
Parsing large DAT files takes a very long time

### ISSUE THREAD

**Issue by chainsawsalad** [emmercm/igir#395]
### Is your feature request related to a problem?

I'm attempting to run `igir` with several DAT files, but I suspect Redump's `IBM PC compatible` DAT file of ~40,000 entries is causing the tool some major problems. **I've been running the tool for 7 days, and it has been stuck on the `parsing DAT files` phase since day 1.** 

I'm not using the most robust of machines, so I acknowledge it would be reasonable for things to be slow, but this is so slow it seems there must be a practical upper limit on DAT sizes.

http://redump.org/downloads/
http://redump.org/datfile/pc/

I suspect I could unblock myself by manually breaking up the large DAT file into multiple smaller ones, but I have not tried this.

### Describe the solution you'd like

More robust logging to indicate the tool is not hanging. Different memory management strategy for compatibility with larger DAT files.

### Additional context

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/2692529/235367983-ce70b701-b0ac-4a8b-935a-febd26800fbc.png">

**Comment by emmercm** [comment]
@chainsawsalad this issue was submitted as a feature request rather than a bug, could you fill out some additional details needed to debug this:

- The entire igir command
- igir version
- Node.js version (if applicable)
- Operating system

**Comment by chainsawsalad** [comment]
Sorry, I considered "speed is a feature" and didn't want to presume this is truly a bug.

Unfortunately I am running the command with tmux, so I lost the ends of the log lines. I will re-run and get all the info you need. Stay tuned.

**Comment by emmercm** [comment]
Anything longer than about ~30sec per DAT I would consider to be a bug somewhere, even more than ~10sec and I would be surprised.

I just tried with `IBM - PC compatible - Datfile (40510) (2023-04-30 19-28-53).zip` and it's definitely the largest of the bunch at 9.9MiB. I daily drive a 2019 Macbook Pro and I noticed it took longer to parse, but it was still within a reasonable amount of time.

I'd be curious what the memory usage of your `node` process is, and if it might be hitting any limits there.

**Comment by chainsawsalad** [comment]
I'm running a Linux box. The machine has 8GB of memory, and covers the rest with swap space. Like I said, not exactly top of the line. The `node` process has a huge virtual memory size (~12GB), but is right now using just 7MB. Feels like it's hung to me...

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/2692529/235370311-7872ce47-019a-444b-86d9-6777d170302b.png">
<img width="642" alt="image" src="https://user-images.githubusercontent.com/2692529/235370467-2c30c107-71d1-452a-817c-085beca5c56d.png">

For clarity, here is the command as well as the rest of the details of the environment:
```
npx igir@latest move test report -vvv \
    --dat "./DATs/Redump/Atari - Jaguar CD Interactive Multimedia System - Datfile (24) (2023-02-25 03-07-48).zip" \
        "./DATs/Redump/IBM - PC compatible - Datfile (40016) (2023-03-12 02-36-10).zip" \
        "./DATs/Redump/NEC - PC Engine CD & TurboGrafx CD - Datfile (541) (2023-04-09 22-11-42).zip" \
        "./DATs/Redump/NEC - PC-88 series - Datfile (1) (2014-10-07 01-25-20)(1).zip" \
        "./DATs/Redump/NEC - PC-98 series - Datfile (107) (2023-03-11 18-20-27)(1).zip" \
        "./DATs/Redump/NEC - PC-FX & PC-FXGA - Datfile (78) (2022-09-14 14-41-02)(1).zip" \
        "./DATs/Redump/Panasonic - 3DO Interactive Multiplayer - Datfile (628) (2023-04-10 00-54-12).zip" \
        "./DATs/Redump/Philips - CD-i - Datfile (1918) (2023-04-11 07-17-26).zip" \
        "./DATs/Redump/SNK - Neo Geo CD - Datfile (111) (2022-09-23 17-55-26)(1).zip" \
        "./DATs/Redump/Sega - Dreamcast - Datfile (1458) (2023-04-09 19-56-43).zip" \
        "./DATs/Redump/Sega - Mega CD & Sega CD - Datfile (540) (2023-04-03 20-10-15).zip" \
        "./DATs/Redump/Sega - Saturn - Datfile (2357) (2023-04-12 19-27-46).zip" \
        "./DATs/Redump/Sony - PlayStation - Datfile (10707) (2023-04-12 22-57-53).zip" \
    --input ~/downloads \
    --output ./Redump/ \
    --dir-dat-name \
    --overwrite-invalid
```
```
igir version: 1.6
Node version: 12
```

**Comment by chainsawsalad** [comment]
I'll also say, I just ran the same command on my Macbook Pro, and it parsed the DATs within 30 seconds, so there's definitely something going on either with the version of Node I'm using or the Linux machine itself. I would understand if you chose to close this ticket.

**Comment by emmercm** [comment]
It's definitely hung on something, maybe the XML parsing. DAT scanning & parsing uses 20 "threads," so the fact your progress bar doesn't indicate the other files were processed definitely points to hanging on `IBM - PC compatible`.

I'll see what else I can find!

**Comment by chainsawsalad** [comment]
Just ran it again on my Macbook, this time using Node v12. Same result as the Linux machine!

**Comment by emmercm** [comment]
I think I found it: `igir` requires Node.js `>=14.18.0` but `npx` doesn't enforce this at all, or even provide you a warning. There are some dependencies that use more modern syntax such as `node:` imports that don't work with older Node.js versions. I'll put in a change to enforce the Node.js version at startup.
