### ISSUE TITLE
Include core-specific output option for Onion/GarlicOS

### ISSUE THREAD

**Issue by chainsawsalad** [emmercm/igir#396]
### Is your feature request related to a problem?

Popular SBC devices like Miyoo Mini and Anbernic RG35XX often run the CFW Onion/GarlicOS, which has it's own expected directory structure. It would be great to have the ability to output following this convention, similar to the Analogue Pocket and MiSTer FPGA options.

### Describe the solution you'd like

`{onion}` option that behaves identically to `{pocket}` and `{mister}`, but uses the directory names Onion expects.

### Additional context

<img width="744" alt="image" src="https://user-images.githubusercontent.com/2692529/235368784-662eeccb-f33d-48a6-b7cd-223f5b0d9db6.png">

See each emulator's magically named folder documented here:
https://github.com/OnionUI/Onion/wiki/Emulators 

https://www.patreon.com/posts/garlicos-for-76561333

**Comment by emmercm** [comment]
It's a good suggestion, I had thought about this previously but haven't made any moves yet.

I had an RG350 that had its battery run dry and wouldn't charge, and sort of gave up on those handhelds when I got my Analogue Pocket. I could likely use some help testing this if you have a device.

**Comment by chainsawsalad** [comment]
I do own an RG35XX running GarlicOS. Happy to help test for you if that's something you'd want.

**Comment by emmercm** [comment]
@chainsawsalad do the emulator-specific folders go at the root of the SD card? Could you happen to provide a `tree -d` of the directories on the SD card?

**Comment by chainsawsalad** [comment]
This is the ROMS partition of the card for GarlicOS 1.3.2. My understanding is that the `Roms` folder structure is identical to Onion. GarlicOS seems to get regular updates, so it's possible more folders will be added per [Onion's Emulators wiki](https://github.com/OnionUI/Onion/wiki/Emulators).

```
./BIOS
./CFW
./Roms
./Roms/GBA
./Roms/AMIGACD
./Roms/PCEIGHTYEIGHT
./Roms/SEVENTYEIGHTHUNDRED
./Roms/SCUMMVM
./Roms/INTELLIVISION
./Roms/MS
./Roms/FIFTYTWOHUNDRED
./Roms/CPS1
./Roms/LYNX
./Roms/DOS
./Roms/ZXS
./Roms/ARCADE
./Roms/GG
./Roms/SEGACD
./Roms/MEGADUCK
./Roms/FBNEO
./Roms/ATARI
./Roms/FC
./Roms/NGP
./Roms/SFC
./Roms/X68000
./Roms/FBA2012
./Roms/FDS
./Roms/MAME2000
./Roms/ODYSSEY
./Roms/PICO
./Roms/COMMODORE
./Roms/PCFX
./Roms/SEGASGONE
./Roms/ZXEIGHTYONE
./Roms/FAIRCHILD
./Roms/VB
./Roms/XONE
./Roms/SGFX
./Roms/PCE
./Roms/TIC
./Roms/PS
./Roms/POKE
./Roms/GBC
./Roms/UZEBOX
./Roms/VECTREX
./Roms/ATARIST
./Roms/GW
./Roms/SATELLAVIEW
./Roms/CPS2
./Roms/GB
./Roms/GB/Imgs
./Roms/MD
./Roms/AMIGA
./Roms/SGB
./Roms/COLECO
./Roms/SUPERVISION
./Roms/MSX
./Roms/CPC
./Roms/PCECD
./Roms/EIGHTHUNDRED
./Roms/NEOGEO
./Roms/NEOCD
./Roms/PCNINETYEIGHT
./Roms/CPS3
./Roms/JAGUAR
./Roms/THIRTYTWOX
./Roms/SUFAMI
./Roms/PANASONIC
./Roms/VIDEOPAC
./Roms/VMU
./Roms/WS
./Roms/QUAKE
./Roms/VIDEOS
./Roms/PORTS
./Roms/APPS
./Saves
```

**Comment by emmercm** [comment]
I just put the pull request up if you were interested in testing:

```shell
git clone --branch emmercm/onionos https://github.com/emmercm/igir.git
cd igir
nvm use
npm ci
ts-node ./index.ts <commands> <options>
```

https://github.com/emmercm/igir/pull/413

**Comment by chainsawsalad** [comment]
Looks pretty good to me after a few tests. There are a handful of unsupported folders, which you're probably aware of. I saw that you already have TODOs for `ZXEIGHTYONE` and `CPS1` / `CPS2` / `CPS3`, but here's the full list supported by Onion that does not have coverage in IGIR:

```
AMIGACD
ARCADE / FBA2012 / FBNEO / MAME2000 
CPS1 / CPS2 / CPS3
DOS
PCFX
PICO
PORTS
SCUMMVM
SGB
TIC
UZEBOX
VMU
ZXEIGHTYONE
```

Happy to test more for anything specific you're looking for.
