### ISSUE TITLE
ERROR: TypeCannot read properties of undefined (reading 'getRomsWithFiles')

### ISSUE THREAD

**Issue by dixius99** [emmercm/igir#473]
### Paste the command

`npx igir@latest report --dat /Users/michael/Downloads/MAME_Dats_256/DATs/MAME\ 0.256.dat --input /Users/michael/Documents/Emulator\ Data/MAME/roms`

### Describe the bug

I just tried to run a report for my MAME ROMs, and while it seems to scan for DATs and ROMs okay, when generating the report, I get the error in the title.

```
✓ Scanning for DATs ············ | 1 unique DAT found
✓ Scanning for ROMs ············ | 12,032 unique ROMs found
✓ Detecting ROM headers ········ | 12,032 ROMs processed
✓ MAME ························· | 6,355/43,920 games, 7/75 BIOSes, 6,355/43,920 retail releases fod
✎ Generating report ············ | ░░░░░░░░░░░░░░░░░░░░░░░░░
ERROR: TypeCannot read properties of undefined (reading 'getRomsWithFiles')
```

I'm pretty sure this is something I'm doing wrong, vs. an actual bug, but not sure what to do to get the report.

### Expected behavior

The command executes without an error and I can access the report.

### Debug logs

[debug.txt](https://github.com/emmercm/igir/files/12003754/debug.txt)

### igir version

1.6.6

### Node.js version

20.4.0

### Operating system

macOS 13.4.1 (22F82)

**Comment by emmercm** [comment]
Highly likely this is a bug with the code, maybe with the new MAME code from v1.6.6. I might not get a chance to dig in depth this week, but I will soon!

**Comment by emmercm** [comment]
Confirmed this behavior with the same progetto-SNAPS DAT.
