### ISSUE TITLE
Invalid count value error

### ISSUE THREAD

**Issue by netwaretcs** [emmercm/igir#557]
### Paste the command

npx igir@latest move zip report --dat _ROMs_dat/ --input _ROMs/roms --output _ROMs-Sorted/ --dir-dat-name --single --prefer-pal --no-bios --no-device --no-demo 

### Describe the bug

![Screenshot 2023-08-06 at 09 03 16](https://github.com/emmercm/igir/assets/67137992/48f6f6d7-f5e8-469e-8451-be83a551d035)

This is a screenshot of the error.

### Expected behavior

I do not expect an error

### Debug logs

I do not have the logs. The second time I run the command with -vvv the error disappeared.

### igir version

1.9.0 (igir@latest)

### Node.js version

18.17

### Operating system

MacOS Ventura

### Additional context

This is not a problem for me, but I hope it can be useful as a report.

**Comment by emmercm** [comment]
I've seen this a few times myself and haven't been able to pinpoint it. I can put in some code to make sure it at least doesn't crash like this.
