### ISSUE TITLE
Add Xbox support to Game Consoles

### ISSUE THREAD

**Issue by dcramer** [emmercm/igir#576]
### Describe the solution you'd like

Right now it appears Xbox (incl. Xbox 360) is one of the major systems not accounted for in the GameConsole handler. Should be simple to add akin to PlayStation etc and dats are available on Redump.

**Comment by dcramer** [comment]
I dont have an immediate need for this, just noticed it when I was going through the Batocera mapping

**Comment by emmercm** [comment]
Thanks for this @dcramer! Right now, `src/types/gameConsole.ts` is really only used to replace `{pocket}`, `{mister}`, and `{onion}` tokens. I don't know of any devices or frontends that support OG Xbox or Xbox 360 right now, so an addition shouldn't be necessary, but let me know if I'm off here!

**Comment by emmercm** [comment]
And as an aside, thank you so much for your sponsorship @dcramer! It means a lot to a free-time project maintainer.

**Comment by dcramer** [comment]
I think Batocera does? If thats wha tyou mean by device/frontend. Which I think is Emulation Station?

**Comment by emmercm** [comment]
I definitely read this before https://github.com/emmercm/igir/pull/575. Feel free to add as many new consoles in there as you'd like!
