### ISSUE TITLE
Error when running "symlink clean"

### ISSUE THREAD

**Issue by docbobo** [emmercm/igir#586]
### Paste the command

```
./bin/igir symlink clean \
  --dat "./MiSTer.DATs/*.dat" \
  --input "./roms/**/*.zip" \
  --output "./MiSTer/{mister}" \
  --dir-letter \
  --no-bios \
  --single \
  --only-retail \
  --prefer-language DE,EN \
  --prefer-region USA,WORLD,EUR,JPN
```

### Describe the bug

When executing the command above, I get the following error at the end and the cleanup operation stops:

```
[11:47:30.966] INFO:  DirectoryCleaner: cleaning files in output
[11:47:31.992] ERROR: MiSTer/Atari5200/A/Atari PAM Diagnostics (USA) (v2.0).zip: no files found
```

First of all, the file quoted above does not exist. There is no indication that it got created during the symlink part. There is the following in the log though:

```
[11:46:18.416] TRACE: CandidateGenerator: Atari - 5200: Atari PAM Diagnostics (USA) (v2.3): found 2 candidates
```

(Please not the version difference though)

### Expected behavior

Cleanup operation finishes successfully.

### Debug logs

n/a

### DAT(s) used

Atari - 5200 (Parent-Clone) (20220405-183755).dat

### igir version

1.9.1

### Node.js version

n/a

### Operating system

Linux

**Comment by emmercm** [comment]
This might be a bug with https://github.com/emmercm/igir/pull/563, I'll have to investigate.
