### ISSUE TITLE
status of fixdat when running igir

### ISSUE THREAD

**Issue by feurry** [emmercm/igir#652]
### Describe the solution you'd like

When igir runs you get status messages

✓ Scanning for DATs ············ | 1 unique DAT found
✓ Scanning for ROMs ············ | 1,885 files found
✓ Nintendo - Nintendo Entertainm | 790/3,098 retail releases written
✓ Cleaning output directory ···· | 1 file recycled
✓ Generating report ············ | /home/user/Documents/igir_2023-09-14T09;35;36.csv

When adding the --fixdat I would expect to see.
✓ Generating fixdat .............| /home/user/Documents/outfolder/Nintendo - Nintendo Entertainment System (Headered) (Parent-Clone) fixdat (20230914-094654).dat

**Comment by emmercm** [comment]
I'll have to think about this one. Right now, there is only one progress bar per DAT, and that progress bar results in the "X/Y ROMs written" message. I think adding the fixdat filename at the end of that would make it too long, but I don't think a log message is appropriate here either.

**Comment by feurry** [comment]
It's not critical, just thought it made sense to print status on the fixdat if the status of the report was being printed. It's visible with -vvv anyway.

Sorry I was slow responding for closed #654. Didn't want to re-open that, but IGNORED wording looks good to me.

**Comment by emmercm** [comment]
I think this is a totally valid suggestion, I'll just have to think about the best way to do it. Maybe in report-only mode it would replace the "X/Y ROMs written" message. I appreciate your suggestion!

And not a problem at all on #654! I wanted to include the change in my big-bang v2 release, so I went ahead with what made the most sense to me.

**Comment by emmercm** [comment]
I think I'm going to need to address this for https://github.com/emmercm/igir/issues/626 as well. I'm going to add a new `dir2dat` command that probably also needs to log its output location.
