### ISSUE TITLE
--filter-regex from a text file

### ISSUE THREAD

**Issue by feurry** [emmercm/igir#655]
### Describe the solution you'd like

I would like to use a text file (game/rom list) as an input filter. I find the AKNF (All Killer No Filler) game lists useful and game lists in general to be useful when sorting roms, especially with FBNeo and MAME.

AKNF
http://forum.arcadecontrols.com/index.php?topic=149708.0

I imagine it working the same as the --filter-regex and exclude everything not listed.

**Comment by emmercm** [comment]
I think the request makes sense. Maybe `igir` should treat a value of `-` as "read from stdin" like a lot of other CLI tools do. So the command would be `igir [commands..] --filter-regex -`. Or maybe it first checks if the param is a file that exists, before using it as a string.

**Comment by feurry** [comment]
"read from stdin" should work. I don't use that a lot, but if it works it works. I was thinking of an -f value or --filter-from-file sort of thing. But that would be another option, and I think you're trying not to add too many more of those.

I was trying --filter-regex (cat mygamelist.txt), but couldn't figure out how to get that to work properly.

**Comment by emmercm** [comment]
`--filter-regex "/$(tr '\n' '|' < mygamelist.txt)/i"` might get you what you want for right now actually.

I'm thinking `--filter-name-regex mygamelist.txt` might be the way to go for this, where it's smart enough to detect if the value is a file.

**Comment by feurry** [comment]
Thanks for the suggestion, but it didn't work. With a gamelist of **1943 - The Battle of Midway (USA)** I get 179 matches. I think it's matching each word. 

I was able to get this to work, in 2 steps. Use sed to create a regex friendly version of the gamelist first, which inserts ^ at the begging of every line, $ at the end of every line, and replacing ( and ) with escaped versions \( and \).

So 
1943 - The Battle of Midway (USA)
becomes 
^1943 - The Battle of Midway \\(USA\\)$

Then use a slightly modified version of the --filter-regex command you provided.
`--filter-regex "$(tr '\n' '|' < glist.txt)"/`

step 1.
`sed -e 's/^/\^/' -e 's/(/\\(/g' -e 's/)/\\)/g' -e 's/$/\$/' gamelist.txt > glist.txt`
step 2.
`npx igir@latest report -d Documents/*.dat -i nes/ --no-bios --filter-regex "$(tr '\n' '|' < glist.txt)"/`

**Comment by emmercm** [comment]
Ah, yeah, the character escaping would trip up the regex, and the line beginning/end markers make sense. You can probably get `sed` inline with the command, like:

```
--filter-regex "$(cat mygamelist.txt | sed ... | tr '\n' '|')"
```

but really I just need to find time for this feature.
