### ISSUE TITLE
Clean current directory based off dat

### ISSUE THREAD

**Issue by cdloh** [emmercm/igir#676]
### Is your feature request related to a problem?

Currently I have large ROM folders that I want to clean up (ie delete ROMs) based off dat files without having to copy them around.

### Describe the solution you'd like

Make the clean command work on a singular input directory with X amount of Dats.

### Additional context

Not sure if this is already possible I've been trying with various command combinations.

**Comment by emmercm** [comment]
If you `move` files from an input directory to the same output directory, without overwriting, then all you should get is file renames. This satisfies the condition of providing a "writing" command, which will let you use the `clean` command. This usage of the same directory for input & output is similar to the default behavior in other ROM managers.

Would that work for you, @cdloh? Or would you want to avoid file renames?

**Comment by cdloh** [comment]
What would it rename the files too? If they're just being renamed to the same file name then thats fine :)

**Comment by emmercm** [comment]
Since you need to provide a DAT in order to generate reports, `igir` would end up renaming your files according to what the DAT has. Would that work, or would it break a custom naming scheme you have?
