### ISSUE TITLE
Adding a {fileReleaseRegion} output path token that is inferred from the file name

### ISSUE THREAD

**Issue by samwelnella** [emmercm/igir#696]
### Is your feature request related to a problem?

Some No-Intro DATs, such as the Atari 2600 P/C XML one, only have region information for some games in the DAT file. When using the `{datReleaseRegion}` output token, games that don't have region information in the DAT are not copied/moved to the output folder at all.

### Describe the solution you'd like

Since No-Intro files have the region information in the filename, I am proposing a new `{fileReleaseRegion}` output path token that infers the region from the ROM's file name. Alternatively, a generic `{releaseRegion}` output token could be used that first tries to get the region from the DAT file and then falls back to using the file name when a `region` tag in the DAT file doesn't exist.

**Comment by emmercm** [comment]
I think `{releaseRegion}` (and `{releaseLanguage}`) is a good suggestion. I did some refactoring work around v1.8.2 (https://github.com/emmercm/igir/pull/530) which should make this relatively easy.
