### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by emmercm** [emmercm/igir#715]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

I'm not a graphic designer. I did a couple of quick SVG logos (in the `docs/` directory) so that the website wasn't using the default MkDocs logo. I picked a ROM chip motif because most other ROM managers do, but I'm not attached to it.

I'd love for a fan of `igir` to help design a new logo, something that's a little more recognizable.

**Comment by adsingh14** [comment]
I'm interested! Before getting assigned, do you have any references in mind?

**Comment by netwaretcs** [comment]
I gave it a try but since I have no indication of what style to use I may have taken the wrong path.

A hieroglyphic between joystick, roms and old arcade cabinets. 
A bit conceptual...

Make of it what you will :D

![Screenshot 2023-11-01 at 12 28 17](https://github.com/emmercm/igir/assets/67137992/add7f1b2-3383-48fd-b1a3-92d6dbaa8cbf)

**Comment by emmercm** [comment]
@netwaretcs I completely lost your incredible contribution among my other notifications, I'm so sorry!

I love this design! I'm a huge fan of two-color, flat logos like this. I think I like the top design better because it better represents the arcade cabinet concept. Maybe there's something with the bottom half of the "R" that could be turned into something that looks like a ROM chip? Or maybe that would throw off the balance, I'm not sure. My other thought is how this might be turned into a square favicon for https://igir.io/, maybe just the "IG" glyphs?

Would you be willing to upload a vector image of this?

**Comment by emmercm** [comment]
@netwaretcs nudging the above message in case it got lost in the shuffle. Again, thank you for your work here!

**Comment by Djabal** [comment]
Hi @emmercm,
I redraw the proposition of @netwaretcs.
I have tried to do a favicon too.

![logo_igir_light](https://github.com/user-attachments/assets/c5c8565b-4d55-49cb-9ff3-ecc255c37cd2)
![logo_igir_dark](https://github.com/user-attachments/assets/af10d29d-6dac-4516-a8ab-0574440ec56e)
![logo_igir_work](https://github.com/user-attachments/assets/30b795a0-7ba9-44b2-a5ac-61c2d419d05c)
![favicon_igir](https://github.com/user-attachments/assets/eae68829-8643-4a74-a7b8-f1305030f54a)
