### ISSUE TITLE
merged strategy missing files

### ISSUE THREAD

**Issue by nottanumber** [emmercm/igir#717]
### Paste the command

looking 👌 but still finding some edge cases

after

```ps
npx igir@latest zip copy test clean report --dat $MAME_EXE --input '.\MAME\**\*' --output .\ROMs-Sorted\ --merge-roms merged
```

followed by

```ps
.\mame ddonpacha
```

### Describe the bug

mame returns

```sh
eeprom-ddonpach.bin WRONG CHECKSUMS:
    EXPECTED: CRC(2df16438) SHA1(4881b70589a97e2420feb6d6e6737273beeff303)
       FOUND: CRC(315fb546) SHA1(7f597107d1610fc286413e0e93c794c80c0c554f)
```

### Expected behavior

correct eeprom-ddonpach.bin is copied to clone folder

### Debug logs

```sh
eeprom-ddonpach.bin WRONG CHECKSUMS:
    EXPECTED: CRC(2df16438) SHA1(4881b70589a97e2420feb6d6e6737273beeff303)
       FOUND: CRC(315fb546) SHA1(7f597107d1610fc286413e0e93c794c80c0c554f)
```

### igir version

2.0.2

### Node.js version

20.6.1

### Operating system

win

**Comment by emmercm** [comment]
You're a legend @nottanumber, please keep the bug reports coming! The documentation on how MAME ListXMLs are supposed to work is really poor, I'm trying to infer a lot of behavior from the pleasuredome DATs.
