### ISSUE TITLE
--prefer-revision-newer doesn't always work

### ISSUE THREAD

**Issue by jmf626** [emmercm/igir#725]
### Paste the command

igir copy --dat "C:\Backup\Recalbox\Workshop\igir-2.0.2-Windows-x64\clonelists\Nintendo - Nintendo Entertainment System (Headered) (Parent-Clone) (20230917-161006).dat" --input "C:\Backup\Recalbox\JuegosRetro\romsets\No-Intro\nes" --output "C:\Backup\Recalbox\JuegosRetro\roms\nes" --no-bios --no-device --no-unlicensed --only-retail --no-debug --no-demo --no-beta --no-sample --no-prototype --no-test-roms --no-aftermarket --no-homebrew --no-bad --single --prefer-language En,Es --prefer-region USA,WORLD,EUR,JPN --prefer-revision-newer

igir copy --dat "C:\Backup\Recalbox\Workshop\igir-2.0.2-Windows-x64\clonelists\Nintendo - Super Nintendo Entertainment System (Parent-Clone) (20230903-114031).dat" --input "C:\Backup\Recalbox\JuegosRetro\romsets\No-Intro\snes" --output "C:\Backup\Recalbox\JuegosRetro\roms\snes" --no-bios --no-device --no-unlicensed --only-retail --no-debug --no-demo --no-beta --no-sample --no-prototype --no-test-roms --no-aftermarket --no-homebrew --no-bad --single --prefer-language En,Es --prefer-region USA,WORLD,EUR,JPN --prefer-revision-newer

### Describe the bug

--prefer-revision-newer doesn't seems to work in certain cases.
For example, this happens with nes games:

- **Choplifter (Japan) (En)** instead **Choplifter (Japan) (En) (Rev 1)**
- **Flipull - An Exciting Cube Game (Japan) (En)** instead **Flipull - An Exciting Cube Game (Japan) (En) (Rev 1)**
- **Punch Out!! (USA)** instead **Mike Tyson's Punch-Out!! (Japan, USA) (En) (Rev 1)**

And with snes games:

- **Jaleco Rally Big Run - The Supreme 4WD Challenge (Japan) (En)** instead **Jaleco Rally Big Run - The Supreme 4WD Challenge (Japan) (En) (Rev 1)**

- **Super Tetris 2 + Bombliss (Japan) (En)** instead **Super Tetris 2 + Bombliss (Japan) (En) (Rev 1)**

In those cases the latest revisions are not obtained. Maybe (en) tag is interfering with the evaluation of revisions?

### Expected behavior

- With the --prefer-revision-newer parameter all chosen games should correspond to the latest revision specified in the DAT.

### Debug logs

[igirnes.zip](https://github.com/emmercm/igir/files/12773542/igirnes.zip)
[igirsnes.zip](https://github.com/emmercm/igir/files/12773543/igirsnes.zip)

### DAT(s) used

https://datomatic.nointro.org/

### igir version

2.0.2

### Node.js version

N/A

### Operating system

win10

**Comment by emmercm** [comment]
@jmf626 could you do me a favor and double-check the bug still exists in v2.0.4? I'm wondering if https://github.com/emmercm/igir/pull/723 accidentally solved this.

**Comment by jmf626** [comment]
@emmercm Hi! I just tried version 2.0.4 and I still get the same results.

**Comment by emmercm** [comment]
I found the bug, it's because `igir` prefers to get a game's language from its region (i.e. `Japan`->`Ja`) vs. using languages in the game title. The examples you provided were very helpful, and somewhat surprising that they were released like that. I'll work on a fix.

**Comment by jmf626** [comment]
I see, so that's what's going on. Congratulations on finding the cause! You're the best!
