### ISSUE TITLE
--prefer-language second check

### ISSUE THREAD

**Issue by jmf626** [emmercm/igir#726]
### Is your feature request related to a problem?

Using **--prefer-language En,Es** gives this result in the following case of a 1G1R snes romset:

**Tintin in Tibet (Europe) (En,Fr,De,Nl)** is chosen instead of  **Tintin in Tibet (Europe) (En,Es,Sv)**

At first glance, it seems fine that the first language chosen is (en) since both ROMs have it. However, the second preferred language is (es).

### Describe the solution you'd like

 Therefore, it would be great if, in the case of a coincidence in the first language, the second one is checked.
In the case of SNES, there are not many occurrences, but it does happen frequently in Game Boy and Game Boy Advance ROMs.

Thanks!

**Comment by emmercm** [comment]
This is a good suggestion. I swore I wrote it this way, but potentially not.

**Comment by emmercm** [comment]
Confirmed I definitely didn't account for this behavior, so I will work on it.
