### ISSUE TITLE
Docs: Steam Deck EmulationStation instructions

### ISSUE THREAD

**Issue by emmercm** [emmercm/igir#737]
### Describe the solution you'd like

Adding instructions for how to sort ROMs for EmulationStation on a Steam Deck.

It probably makes the most sense to add this to https://igir.io/usage/desktop/emulationstation/.

**Comment by maxexcloo** [comment]
What additional context are you looking for? As far as I could tell it's mostly the folder naming that would need to be updated?

**Comment by maxexcloo** [comment]
I think this ticket is covered by this: https://github.com/emmercm/igir/pull/943
