### ISSUE TITLE
--no-program flag

### ISSUE THREAD

**Issue by lucaorio** [emmercm/igir#753]
My understanding is that one can easily exclude all roms marked as `(Program)` by:
```
--filter-regex-exclude "/(\(Program\))/i"
```

Still, `(Program)` is fairly common in the No-Intro set: I was wondering if a `--no-program` flag could be something interesting to add!

**Comment by lucaorio** [comment]
> The documentation on No-Intro's naming conventions is fairly weak. Is `(Program)` used to categorize non-games, do you know?

I don't know the exact usage of that tag, but it looks like about small software and diagnostic tools.
I ran a quick search, and there are quite a few of them; definitely non-game material!

```
Atari - 7800: 1
Bandai - WonderSwan: 11
Bandai - WonderSwan Color: 6
Coleco - ColecoVision: 1
Commodore - Commodore 64: 68
Commodore - Commodore 64 (Tapes): 5
Commodore - VIC-20: 50
Microsoft - MSX: 49
Microsoft - MSX2: 4
Nintendo - Game Boy Advance: 3
Nintendo - Nintendo Entertainment System (Headered): 60
Nintendo - Super Nintendo Entertainment System: 5
Sega - 32X: 1
Sega - Game Gear: 2
Sega - Mega Drive - Genesis: 23
Sega - SG-1000: 33
VTech - CreatiVision: 4
```

**Comment by maxexcloo** [comment]
I've been handling this using retool to create the DATs used by IGIR: https://github.com/unexpectedpanda/retool

**Comment by emmercm** [comment]
@maxexcloo Retool is great. Are there any other filters that you find useful?

**Comment by maxexcloo** [comment]
I’ve literally been using all of them except for games, haven’t had any trouble so far!
