### ISSUE TITLE
Handling TOSEC alternates and duplicates across different rom types

### ISSUE THREAD

**Issue by lucaorio** [emmercm/igir#754]
TOSEC packs are a nightmare!

Is there a way to filter out alternate versions natively with igir?
```js
• Legend of TOSEC, The (1986)(Devstudio)(US) // keep this only
• Legend of TOSEC, The (1986)(Devstudio)(US)[a]
• Legend of TOSEC, The (1986)(Devstudio)(US)[a2]
• Legend of TOSEC, The (1986)(Devstudio)(US)[b]
• Legend of TOSEC, The (1986)(Devstudio)(US)[cr]
```

Also, do you have any suggestion on how to filter out duplicates across different extension-based sets (i.e., `.z80` vs. `.dsk`):
```js
• Legend of TOSEC, The (1986)(Devstudio)(US).dsk // keep this only
• Legend of TOSEC, The (1986)(Devstudio)(US).z80
```

**Comment by emmercm** [comment]
Agreed, the TOSEC naming conventions are difficult because of how inconsistent they can be. See my attempt at handling them here: https://github.com/emmercm/igir/blob/9106ac0d3a48d5aa1b5e1e905ad25adf61fb5008/src/modules/datParentInferrer.ts#L138-L145

As of `igir` v2.0.0, TOSEC DATs should have parent/clone information inferred, so 1G1R `--single` should work. In your first example, `--prefer-parent` might work, or maybe `--prefer-retail`. Let me know if existing options don't handle all of your cases.

---

For the differing ROM extensions, do you happen to have some examples from one of the DATs, or an example console to check out?

**Comment by lucaorio** [comment]
Let's say I have two folders:
- TOSEC/Sinclair ZX Spectrum - Games - [Z80]
- TOSEC/Sinclair ZX Spectrum - Games - [DSK]

And I'm running the command below.
```sh
npx igir@latest copy test clean \
  --dat "dat/Sinclair*.dat" \
  --input "TOSEC/" \
  --output "TOSEC-trimmed" \
  --dir-mirror \
  --single \
  --prefer-parent \
  --prefer-region USA,WORLD,EUR,JPN \
  --filter-regex-exclude "/(\[needs tape load\]|\[re-release\])/i"
```

---

The _[DSK]_ folder gets trimmed a little, but there are some unexpected results:
- `Amnesia v1.02 (2015-12-05)(Huelvy)(+3)(es).dsk` is picked over `Amnesia v1.02 (2015-12-05)(Huelvy)(+3).dsk`
- `Corruption (1988)(Rainbird)(+3)[a2].dsk` still lives alongside `Corruption (1988)(Rainbird)(+3).dsk`\

The _[Z80]_ folder gets trimmed a lot, but there are some unexpected results in there, too:
- `3D Maze of Gold (1982)(Gilsoft International)(16K)[a].z80` is removed correctly, but `3D Maze of Gold (1982)(Gilsoft International)(16K)[a2].z80` still lives alongside `3D Maze of Gold (1982)(Gilsoft International)(16K).z80`

Do you know if I'm doing anything wrong here?

---

Regarding the second point, let's say after the trimming, I have two files:
- `Sinclair ZX Spectrum - Games - [Z80]/Action Force - International Heroes (1987)(Virgin Games).z80`
- `Sinclair ZX Spectrum - Games - [DSK]/Action Force - International Heroes (1987)(Virgin Games)(+3).dsk`

Is there a way to remove one of the two?

**Comment by emmercm** [comment]
There isn't a way to deduplicate across different DATs at the moment, but maybe this would work:

- (all input DATs get scanned as usual)
- (`--dat-*-regex*` DAT filter options are applied as usual)
- A new option to combine all input DATs into one would be applied
- (parent/clone inference from v2.0.0 would then think these games are clones):

  ```
  dsk: Action Force - International Heroes (1987)(Virgin Games)(+3)"
  z80: Action Force - International Heroes (1987)(Virgin Games)
  z80: Action Force - International Heroes (1987)(Virgin Games)[a]
  z80: Action Force - International Heroes (1987)(Virgin Games)[a2]
  z80: Action Force - International Heroes (1987)(Virgin Games)[a3]
  ```

- A new option to prefer one file name over another (`--prefer-rom-name <regex>` or similar) would rank games with `.z80` files above others

Maybe something like that. Thoughts?

**Comment by lucaorio** [comment]
This would be **awesome**. Cleaning up those TOSEC manually is not good for one’s health haha

**Comment by emmercm** [comment]
@lucaorio you should be able to accomplish this with the new options:

```shell
npx igir@latest copy test clean \
  --dat "dat/Sinclair*.dat" \
  --input "TOSEC/" \
  --output "TOSEC-trimmed" \
  --dir-mirror \
  --single \
  --prefer-parent \
  --prefer-region USA,WORLD,EUR,JPN \
  --filter-regex-exclude "/(\[needs tape load\]|\[re-release\])/i" \
  --dat-combine \
  --prefer-rom-regex "\.z80$"
```
