### ISSUE TITLE
Very slow working across network

### ISSUE THREAD

**Issue by samuelcole** [emmercm/igir#770]
### Is your feature request related to a problem?

Howdy!

First of all, I super love this application, the ergonomics are great, and I'm a JavaScript engineer, so I love that I can read the source code.

I'm trying to run `igir` against full 7z compressed romsets for Analogue Pocket platforms (snes, nes, gb, gbc, gba, gg, md), and I would like to keep those romsets on my NAS. The problem is that I am running igir on SMB mounts, which is obviously very slow.

### Describe the solution you'd like

It seems like a few steps extracts the file into memory, because those older platforms generally fall under the `MAX_MEMORY_FILE_SIZE`. Would it be possible/more efficient to pull the files into `tmpdir` first, and then work on the local volume?

In hindsight, I could have done that manually: by downloading my working files local, and then uploading the results back to the NAS, but now I'm 20 hours into an `igir` run and sunk cost fallacy.

Also, I tried running igir from the NAS itself (it's a Synology, with SSH+node), but I ran out of memory pretty quick.

**Comment by emmercm** [comment]
Hi @samuelcole, I'm glad you like the project!

I haven't tried running over SMB myself yet, but I bet it would be slow. The Node.js libraries for 7zip, in particular, are fairly bad; it actually has to extract to a temp file first before writing. The zip library can read to a stream, but the 7zip uses a standalone 7za binary.

Are you seeing a slowdown in scanning, or writing? Scanning I _think_ should be relatively fast, the 7za binary shouldn't need to extract any files.

**Comment by samuelcole** [comment]
I didn't get to writing, ha:

1. Scanning took about 10 hours
2. Extracting ROM header data was closing in at 20 hours before I aborted the whole thing.

I ended up setting up a rsync server on my NAS, and then using the rsync protocol to sync my directory to my local computer (~20 minutes), ran igir over everything (10 minutes), and synced it back to my NAS (~20 minutes). Less than an hour.

I think my feedback is that there seems to be a lot of reading, which seems like it could be consolidated:
1. Extract all files to local/fast `tmpdir`
2. Scan files
3. Read headers
4. Zip files, and place them in `output` etc

My other dream would be to support remote file protocols for input/output arguments ftp/sftp/rsync etc, so that I wouldn't have to mount or copy anything.

**Comment by emmercm** [comment]
First thought: there is probably some optimization I can do to skip header processing if:

- No DAT is marked "unheadered" (causing some automatic header removal)
- The user hasn't requested header removal explicitly

---

Question about your rsync setup, how many concurrent files was it reading and writing? I've been thinking about reducing the default number that `igir` will read and write.

And I was also thinking recently about FTP and SFTP, with paths in a typical URI form (i.e. `ftp://username:password@my-ftp.com/`). I haven't done any research on what's available for Node.js just yet.

**Comment by samuelcole** [comment]
My understanding is that rsync doesn't have concurrency (it transfers files as fast as it can one at a time), because it is disk+network-bound, not cpu-bound, there's no advantage to concurrency (there's only one "pipe" available anyways)

Every single time I've used Samba for something intensive, I've regretted it (network mounts are so tempting, though!) So I'm not sure how much hope there is in supporting my Samba use-case.

Would love ftp+sftp support!

**Comment by emmercm** [comment]
I'll try my hand at a band-aid that reduces concurrency when a network share is detected, that should help.

I've definitely caused myself some situations of high concurrency, and even on an SSD, it can slow everything to a crawl. https://github.com/emmercm/igir/pull/771 was a recent example.

**Comment by emmercm** [comment]
@samuelcole if you're interested in beta testing a new option, I'm adding a `--reader-threads <threads>` debug option to match the existing `--writer-threads <threads>` option in https://github.com/emmercm/igir/pull/778.

There's a comment in the PR about how you can test the branch, and the usage would end up looking like:

```shell
igir [commands..] --input "//NAS/ROMs" [options] --reader-threads 1
```

**Comment by emmercm** [comment]
And since you're using 7zip files, the https://github.com/emmercm/igir/pull/772 fix that I released in v2.0.7 today might have positive performance impacts for you.

**Comment by emmercm** [comment]
Better yet @samuelcole, https://github.com/emmercm/igir/pull/785 should do what you want. It will limit concurrent file reads per drive, and it should limit Samba servers to 1 file at a time.

What OS are you on? And could you paste your full igir command, with file paths (feel free to anonymize them)? I want to make sure I do some more testing on my end.

**Comment by samuelcole** [comment]
Holy cow, thank you! I'm obviously less motivated now that my sd card is loaded up, but I'm super impressed you found something actionable in my wishy washy issue!
