### ISSUE TITLE
igir creates a lot of empty files for certain libretro dat files

### ISSUE THREAD

**Issue by juliadin** [emmercm/igir#822]
### Paste the command

`npm exec --yes -- 'github:emmercm/igir#main' move --dat 'https://raw.githubusercontent.com/libretro/libretro-database/master/dat/Nintendo%20-%20Wii.dat' -i testsrc/ -o testdest/`

### Describe the bug

assuming testsrc/ contains just an empty file and testdest/ is empty or doesn't exist, igir will create a lot of .iso files in testdest/ with 0 bytes

### Expected behavior

igir should to my expectation not create any files since none of the roms are found

### Debug logs

[igir_debug.log](https://github.com/emmercm/igir/files/13437846/igir_debug.log)

### DAT(s) used

https://raw.githubusercontent.com/libretro/libretro-database/master/dat/Nintendo%20-%20Wii.dat

### igir version

2.1.1

### Node.js version

18.18.2

### Operating system

Debian Linux 12

### Additional context

i noticed that this happens with the gamecube, wii U and ps3 dats in the same dir, too. They all have in common that the .dat files do not mention checksums for the roms.

**Comment by juliadin** [comment]
This also leads to igir falsely reporting that the dat is 'complete' ... which it does - to be fair - to the best of it's knowledge considering the .dats do neither contain a file size nor a checksum.

**Comment by juliadin** [comment]
I think it’s a good solution. Sounds very annoying to deal with from the software side. Sorry to hear that. 

Would it be possible to not even count games that have no roms? or deal with them in the summary lines differently? like `… 1/3 retail releases written, 4422 releases with incomplete entries`? I’d think that would be a little more obvious

**Comment by emmercm** [comment]
Fixed by https://github.com/emmercm/igir/pull/835

**Comment by juliadin** [comment]
Thanks a lot! 🫶
