### ISSUE TITLE
Igir fails on corrupted Zip files

### ISSUE THREAD

**Issue by deelowe** [emmercm/igir#853]
### Paste the command

igir copy zip test clean report fixdat \
  --dat "./No-Intro*.zip" \
  --dat-name-regex-exclude "/encrypted/i" \
  --input "./" \
  "${INPUTS[@]}" \
  --patch "./Patches/" \
  --output "./No-Intro/" \
  --dir-dat-name \
  --overwrite-invalid

### Describe the bug

When reading a corrupted zip file, igir will crash. This can be a pain whenever scanning large directories.

### Expected behavior

It would be good if igir tested zip files before attempting to open them, this way the file can be skipped. Perhaps this can be a command option?

### Debug logs

Unfortunately, I do not have a debug log. Hopefully the issue is straight forward enough to reproduce.

### igir version

2.2.0

### Node.js version

N/A

### Operating system

Ubuntu 22.04.3 LTS

**Comment by deelowe** [comment]
Adding more context. Igir is an excellent tool for my use-case (command line, easily scriptable, supports moves & copies, supports file and folder renaming, etc). That said, in order to process large collections, error handling of files and folders likely needs to be looked out. I'm having to hand hold the tool as it seems to fail at the slightest issue. So far, I've noticed that igir will fail on the following issues:

- Empty directories (input and patch encountered so far)
- Corrupted zip file
- "Unhandled Err" Events (cannot debug as error message doesn't provide context)

See below for a screenshot of the unhandled exception.

![Screenshot 2023-12-18 112936](https://github.com/emmercm/igir/assets/221145/7704801f-c60f-47ee-98ad-09ad6dd09c28)

**Comment by emmercm** [comment]
Hi @deelowe, do you happen to know why those zip files are corrupted, or how they were created? That will help me be able to reproduce and solve. The screenshot looks to be related.

**Comment by emmercm** [comment]
I tried creating a bad zip and then running `igir` against it like this:

```shell
$ cat <file.zip> | head -c 1024 > dummy.zip
$ igir report --input dummy.zip --dat "No-Intro*.zip"

 ______   ______   ______  _______  
|      \ /      \ |      \|       \ 
 \$$$$$$|  $$$$$$\ \$$$$$$| $$$$$$$\
  | $$  | $$|    \  | $$  | $$    $$   ROM collection manager
  | $$  | $$|    \  | $$  | $$    $$   https://igir.io/
  | $$  | $$ \$$$$  | $$  | $$$$$$$\
 _| $$_ | $$__| $$ _| $$_ | $$  | $$   v2.2.0
|   $$ \ \$$    $$|   $$ \| $$  | $$
 \$$$$$$  \$$$$$$  \$$$$$$ \$$   \$$


✓ Scanning for DATs ·········· | 276 unique DATs found
ERROR: dummy.zip: failed to parse file: FILE_ENDED
✓ Scanning for ROMs ·········· | 0 files found
✓ Generating report ·········· | <redacted>/igir_2023-12-19T20;57;47.csv
```

but it was handled successfully as shown.

Your output has multiple files that were handled gracefully, just the one that wasn't. I might need an upload of the bad zip file, but it likely contains copyrighted material.

Separately, what's the cause of so many bad zip files in your directory?

**Comment by deelowe** [comment]
Understood.

I'm processing my entire library of files on my NAS. Some are likely old/corrupted and I just never noticed.

I'll try to narrow down which ones are giving me trouble and provide some examples. Unfortunately, with the way unzipper fails, it's not showing me which file is the issue.

**Comment by deelowe** [comment]
I've found one file that crashes unzipper with a "Error: FILE_ENDED" exception.

Here's a link to the offending file and screenshots: https://drive.google.com/drive/folders/16503Tu6BPyRMwgDxZQ9mlOCnnGJyvsRg

**Comment by emmercm** [comment]
@deelowe I'm able to reproduce with that file on my end, thank you! I'll continue to investigate.
