### ISSUE TITLE
spawnSync EBADF error since v2.1.2

### ISSUE THREAD

**Issue by jstapels** [emmercm/igir#856]
### Paste the command

On both v2.1.2 and v2.2.0 I get a strange spawnSync error from `node-disk-info`. Things work just fine on v2.1.1, so I suspect it was a change in one of the transient dependencies. I did a cursory glance at the change for v2.1.2 but nothing jumped out, if I get more time I'll do some more digging. Let me know if you want me to run anything.

My exact command is:
`npx igir@2.1 copy zip report clean --dat DATs/FinalBurn\ Neo\ \(ClrMame\ Pro\ XML,\ Arcade\ only\).dat --input ROMs/FinalBurnNeo/roms/ --output "batocera/roms/fbneo" --only-retail --merge-roms fullnonmerged --single --prefer-language EN --prefer-region USA,WORLD,EUR,JPN`

### Describe the bug

```console
ERROR: spawnSync /bin/sh EBADF
ERROR:     at Object.spawnSync (node:internal/child_process:1124:20)
ERROR:     at spawnSync (node:child_process:876:24)
ERROR:     at Object.execSync (node:child_process:957:15)
ERROR:     at Utils.execute (/Users/jstapels/.npm/_npx/d930de4c5e9892ff/node_modules/node-disk-info/dist/utils/utils.js:53:32)
ERROR:     at Darwin.run (/Users/jstapels/.npm/_npx/d930de4c5e9892ff/node_modules/node-disk-info/dist/platforms/darwin.js:23:36)
ERROR:     at /Users/jstapels/.npm/_npx/d930de4c5e9892ff/node_modules/node-disk-info/dist/index.js:27:50
ERROR:     at new Promise (<anonymous>)
ERROR:     at Object.getDiskInfo (/Users/jstapels/.npm/_npx/d930de4c5e9892ff/node_modules/node-disk-info/dist/index.js:15:12)
ERROR:     at FsPoly.<anonymous> (file:///Users/jstapels/.npm/_npx/d930de4c5e9892ff/node_modules/igir/dist/src/polyfill/fsPoly.js:65:46)
ERROR:     at Generator.next (<anonymous>)
ERROR:     at file:///Users/jstapels/.npm/_npx/d930de4c5e9892ff/node_modules/igir/dist/src/polyfill/fsPoly.js:7:71
ERROR:     at new Promise (<anonymous>)
ERROR:     at __awaiter (file:///Users/jstapels/.npm/_npx/d930de4c5e9892ff/node_modules/igir/dist/src/polyfill/fsPoly.js:3:12)
ERROR:     at FsPoly.disks (file:///Users/jstapels/.npm/_npx/d930de4c5e9892ff/node_modules/igir/dist/src/polyfill/fsPoly.js:64:16)
ERROR:     at DriveSemaphore.<anonymous> (file:///Users/jstapels/.npm/_npx/d930de4c5e9892ff/node_modules/igir/dist/src/driveSemaphore.js:32:40)
ERROR:     at Generator.next (<anonymous>)
```

### Expected behavior

On v2.1.1 it will go through and build all my FBNeo 1G1Rs.

### Debug logs

```
 ______   ______   ______  _______  
|      \ /      \ |      \|       \ 
 \$$$$$$|  $$$$$$\ \$$$$$$| $$$$$$$\
  | $$  | $$|    \  | $$  | $$    $$   ROM collection manager
  | $$  | $$|    \  | $$  | $$    $$   https://igir.io/
  | $$  | $$ \$$$$  | $$  | $$$$$$$\
 _| $$_ | $$__| $$ _| $$_ | $$  | $$   v2.1.2
|   $$ \ \$$    $$|   $$ \| $$  | $$
 \$$$$$$  \$$$$$$  \$$$$$$ \$$   \$$


[15:04:04.730] WARN:  Node.js v21 has a very short support window (ending on Fri May 31 2024), you should consider using an LTS version
[15:04:04.742] INFO:  DATScanner: scanning DAT files
[15:04:04.750] DEBUG: DATScanner: found 1 DAT file
[15:04:04.750] DEBUG: DATScanner: enumerating DAT archives
[15:04:04.765] DEBUG: DATScanner: parsing 1 DAT file
[15:04:04.781] TRACE: DATScanner: DATs/FinalBurn Neo (ClrMame Pro XML, Arcade only).dat: attempting to parse 11.3MiB of XML
[15:04:05.490] TRACE: DATScanner: DATs/FinalBurn Neo (ClrMame Pro XML, Arcade only).dat: parsed XML, deserializing to DAT
[15:04:06.115] TRACE: DATScanner: DATs/FinalBurn Neo (ClrMame Pro XML, Arcade only).dat: 81.5GiB of 7,341 games, 2,453 parents parsed
[15:04:06.122] INFO:  DATScanner: done scanning DAT files
Scanning for DATs ... 1 unique DAT found
[15:04:06.123] INFO:  ROMScanner: scanning ROM files
[15:04:06.312] NOTICE: An update is available for igir: v2.2.0
[15:04:06.458] DEBUG: ROMScanner: found 7,296 ROM files
[15:04:56.402] INFO:  ROMScanner: done scanning ROM files
[15:04:56.403] INFO:  ROMHeaderProcessor: processing file headers
 
[15:04:56.404] ERROR: spawnSync /bin/sh EBADF
[15:04:56.404] ERROR:     at Object.spawnSync (node:internal/child_process:1124:20)
[15:04:56.404] ERROR:     at spawnSync (node:child_process:876:24)
[15:04:56.404] ERROR:     at Object.execSync (node:child_process:957:15)
[15:04:56.404] ERROR:     at Utils.execute (/Users/jstapels/.npm/_npx/8e5abd7c373bda05/node_modules/node-disk-info/dist/utils/utils.js:53:32)
[15:04:56.404] ERROR:     at Darwin.run (/Users/jstapels/.npm/_npx/8e5abd7c373bda05/node_modules/node-disk-info/dist/platforms/darwin.js:23:36)
[15:04:56.404] ERROR:     at /Users/jstapels/.npm/_npx/8e5abd7c373bda05/node_modules/node-disk-info/dist/index.js:27:50
[15:04:56.404] ERROR:     at new Promise (<anonymous>)
[15:04:56.404] ERROR:     at Object.getDiskInfo (/Users/jstapels/.npm/_npx/8e5abd7c373bda05/node_modules/node-disk-info/dist/index.js:15:12)
[15:04:56.404] ERROR:     at FsPoly.<anonymous> (file:///Users/jstapels/.npm/_npx/8e5abd7c373bda05/node_modules/igir/dist/src/polyfill/fsPoly.js:65:46)
[15:04:56.404] ERROR:     at Generator.next (<anonymous>)
[15:04:56.404] ERROR:     at file:///Users/jstapels/.npm/_npx/8e5abd7c373bda05/node_modules/igir/dist/src/polyfill/fsPoly.js:7:71
[15:04:56.404] ERROR:     at new Promise (<anonymous>)
[15:04:56.404] ERROR:     at __awaiter (file:///Users/jstapels/.npm/_npx/8e5abd7c373bda05/node_modules/igir/dist/src/polyfill/fsPoly.js:3:12)
[15:04:56.404] ERROR:     at FsPoly.disks (file:///Users/jstapels/.npm/_npx/8e5abd7c373bda05/node_modules/igir/dist/src/polyfill/fsPoly.js:64:16)
[15:04:56.404] ERROR:     at DriveSemaphore.<anonymous> (file:///Users/jstapels/.npm/_npx/8e5abd7c373bda05/node_modules/igir/dist/src/driveSemaphore.js:32:40)
[15:04:56.404] ERROR:     at Generator.next (<anonymous>)
```

### DAT(s) used

FinalBurn Neo  (ClrMame Pro XML, Arcade only).dat

### igir version

2.1.2

### Node.js version

v21.5.0

### Operating system

macOS 14.2.1 (23C71)

**Comment by maxexcloo** [comment]
Same error here with the same environment...

**Comment by emmercm** [comment]
Fascinating, `node-disk-info` hasn't been updated in 3 years, so maybe it's a lockfile update? I'll see what I can find here.

**Comment by emmercm** [comment]
@jstapels @maxexcloo can you check if this command works correctly on your machines:

```shell
df -P | awk 'NR > 1'
```

https://github.com/cristiammercado/node-disk-info/blob/fc6631d7e055fa47df7f9bf1bf4fc44f7502ae1b/src/utils/constants.ts#L19

**Comment by jstapels** [comment]
Yep, no issues.

**Comment by jstapels** [comment]
I also have no issues if I just launch node and use `node-disk-info`...

```
❯ node                                                                          jstapels@macstudio
Welcome to Node.js v21.5.0.
Type ".help" for more information.
> const nodeDiskInfo = require('node-disk-info');
undefined
> nodeDiskInfo.getDiskInfo()
Promise {
  [
    Drive {
      _filesystem: '/dev/disk3s1s1',
      _blocks: 1942700360,
      _used: 19774392,
      _available: 188714448,
      _capacity: '10%',
      _mounted: '/'
    },
<<<etc. etc. etc.>>>
```

**Comment by emmercm** [comment]
I thought this might have been a macOS 14.2 issue since I was on 14.1.1, but I just updated to 14.2.1 and haven't been able to reproduce it yet.

**Comment by emmercm** [comment]
@jstapels do you still have the issue if you use Node.js 20 or 18?

**Comment by jstapels** [comment]
It fails the same on Node 20 and 18. I suspect this might be a timing problem with node-disk-info reusing the file descriptor. If I can figure out how, I'll try changing the calls in your code from `diskInfo` to `diskInfoSync`

**Comment by jstapels** [comment]
I just realized that I don't have this issue if I limit the number of ROMs files it handles at once. So if I run it on a full collection (75k), the issue happens. Where if I limit it to just a few thousand, no issue.

Are you making a call to `getDiskInfo` for every single ROM file you're about to write? I wonder if this is happening because the program is running out of file descriptors.

**Comment by jstapels** [comment]
So just to follow-up on this a bit, I think the issue is in your `DriveSemaphore`. I don't really know typescript, but it looks like you have a call to get the disk info _inside_ the map, where you either want it outside of the map (so it doesn't get run thousands of times), or inside your map limit (so it gets recalculated and limited).

In this routine...

```typescript
  /**
   * Run some {@link runnable} for every value in {@link files}.
   */
  async map<K extends File | string, V>(
    files: K[],
    runnable: (file: K) => (V | Promise<V>),
  ): Promise<V[]> {
    const disks = await FsPoly.disks();   // <-- !!! I THINK THIS IS THE ISSUE !!!

    // Limit the number of ongoing threads to something reasonable
    return async.mapLimit(
      files,
      Constants.MAX_FS_THREADS,
      async (file, callback: AsyncResultCallback<V, Error>) => {
        try {
          const val = await this.processFile(file, runnable, disks);
          callback(undefined, val);
        } catch (error) {
          if (error instanceof Error) {
            callback(error);
          } else if (typeof error === 'string') {
            callback(new Error(error));
          } else {
            callback(new Error('failed to execute runnable'));
          }
        }
      },
    );
  }
```

**Comment by jstapels** [comment]
So caching the results from the `getDiskInfo` did resolve the issue. I would have submitted a PR, but it looks like you purposely removed caching these results. So for now, here's the patch.

```diff
diff --git a/src/polyfill/fsPoly.ts b/src/polyfill/fsPoly.ts
index 9785c06..a86565a 100644
--- a/src/polyfill/fsPoly.ts
+++ b/src/polyfill/fsPoly.ts
@@ -16,6 +16,8 @@ export default class FsPoly {
   // Assume that all drives we're reading from or writing to were already mounted at startup
   public static readonly DRIVE_MOUNTS = FsPoly.disksSync();
 
+  private static readonly DISK_INFO = nodeDiskInfo.getDiskInfo();
+
   static async canSymlink(tempDir: string): Promise<boolean> {
     const source = await this.mktemp(path.join(tempDir, 'source'));
     await this.touch(source);
@@ -57,7 +59,7 @@ export default class FsPoly {
   }
 
   static async disks(): Promise<string[]> {
-    const disks = await nodeDiskInfo.getDiskInfo();
+    const disks = await FsPoly.DISK_INFO;
     return disks
       .filter((drive) => drive.available > 0)
       .map((drive) => drive.mounted)
@@ -104,7 +106,7 @@ export default class FsPoly {
     }
 
     const resolvedPath = path.resolve(normalizedPath);
-    const drives = await nodeDiskInfo.getDiskInfo();
+    const drives = await FsPoly.DISK_INFO;
     const filePathDrive = drives
       // Sort by mount points with the deepest number of subdirectories first
       .sort((a, b) => b.mounted.split(/[\\/]/).length - a.mounted.split(/[\\/]/).length)
```

**Comment by emmercm** [comment]
@jstapels thank you for such a deep dive into this issue, it is incredibly helpful!

I wouldn't have expected this exact issue, because the call to `FsPoly.disks()` is only performed once per mapping, rather than per item being mapped. Per item would definitely have been egregious.

Could you try the attempted fix in https://github.com/emmercm/igir/pull/878, I'm wondering if a simple backoff & retry strategy is enough to fix this.

**Comment by jstapels** [comment]
> I wouldn't have expected this exact issue, because the call to `FsPoly.disks()` is only performed once per mapping, rather than per item being mapped. Per item would definitely have been egregious.

Are you sure about that? In my testing, I was finding this call to happen quite a bit, and then further down the call to `FsPoly.isSamba()` also ends up making a call to `nodeDiskInfo.getDiskInfo()` (which would result in the EBADF as well when dealing with a lot of files). I would suggest you add a debug trace and you'll see that you're calling for the disk info a multitude of times.

Perhaps you could explain what you're trying to do? Is the concern that the disk info could change underneath your during a very long operation, which is why you don't want to call it once up front?

When I get a chance later I can try your out fix, but if I'm honest, I'm not sure that's a good approach. I can almost guarantee it's going to fail in the same way.

**Comment by emmercm** [comment]
🤦 you're absolutely right, I was laser-focused on `FsPoly.disks()` and not `getDiskInfo()` more widely. `FsPoly.isSamba()` is likely the culprit.

> Perhaps you could explain what you're trying to do? Is the concern that the disk info could change underneath your during a very long operation, which is why you don't want to call it once up front?

That's exactly the thinking. However, this likely isn't a problem since all options are provided up-front. I'll plan on taking your caching suggestion here.

**Comment by jstapels** [comment]
Thanks!
