### ISSUE TITLE
Out of memory crash

### ISSUE THREAD

**Issue by TheBrainScrambler** [emmercm/igir#913]
### Paste the command

```igir report -d "/hone/user/No-Intro Love Pack (Standard) (2024-01-27).zip" -i <gamefolder>```

### Describe the bug

When using the Standard version of No-Intro, No-Intro Love Pack (Standard) (2024-01-27).zip, instead of the PC XML, igir crashes with an out of memory error.

### Expected behavior

When using the PC XML version, it doesn't crash. "No-Intro Love Pack (PC XML) (2024-02-06).zip" is known to work

### Debug logs

[igir.log](https://github.com/emmercm/igir/files/14184591/igir.log)

### DAT(s) used

[No-Intro Love Pack (Standard) (2024-01-27).zip](https://0x0.st/HdZK.zip)

### igir version

v2.3.0

### Node.js version

According to the crash logs, 20.11.0 allthough I run this as a standalone

### Operating system

Nixos 23.11

### Additional context

Kind of related to https://github.com/emmercm/igir/issues/885, allthough I'm getting an out of memory error while he gets "too many open files".

Notice also this:
```
✓ Scanning for DATs ·········· | 287 unique DATs found
✓ Scanning for ROMs ·········· | 1,140 files found
```
The PC XML version has only 287 DATs, while the Standard version has 305. I wonder why there is this difference ?

**Comment by emmercm** [comment]
@TheBrainScrambler I'll attempt to reproduce, but in the mean time could you upload your `No-Intro Love Pack (Standard) (2024-01-27).zip` in case there's something strange with those DATs, specifically?

**Comment by emmercm** [comment]
@TheBrainScrambler can you try this again on your machine now that #915 is merged?

You can do it with this command:

```shell
npm exec --yes -- "github:emmercm/igir#main" [commands..] [options]
```

**Comment by emmercm** [comment]
Or the new v2.4.0 build would also have the fix.

**Comment by TheBrainScrambler** [comment]
I've updated my original comment to include a link to the DATs.

v2.4.0 crashes with the same error as v2.2.1 (which I forgot to mention) and v2.3.0

**Comment by emmercm** [comment]
@TheBrainScrambler how much memory does your device have, or how much memory is allocated to the VM?

**Comment by emmercm** [comment]
> Have you been able to reproduce it ?

Unfortunately, I have not been able to on my M2 MacBook Air with 16GB of RAM.

> I just don't get why the Standard version is ~3x larger than the PC XML version ?

I'm not entirely sure either, and I don't have the bandwidth to dig too deep. I know the "standard" zip has about 15 more files in it, but that wouldn't explain 3x.

> to expose a flag to increase the heap size

I don't believe this can be changed at runtime, and I don't think it would be appropriate for me to change the default. But this would make for a good section in a troubleshooting section of the documentation.

---

There are a number of PRs I've put in over the last few days to try to reduce the memory footprint, I'm looking to release a version today.

**Comment by emmercm** [comment]
@TheBrainScrambler v2.4.1 was just released with some memory improvements, let me know how that works for you without modifying any heap settings.

**Comment by TheBrainScrambler** [comment]
> @TheBrainScrambler v2.4.1 was just released with some memory improvements, let me know how that works for you without modifying any heap settings.

It works ! Thanks !

**Comment by unexpectedpanda** [comment]
> I just don't get why the Standard version is ~3x larger than the PC XML version ?

Decompressing the ZIP files holds the answer. The missing files take up 115MB uncompressed, or 38.5MB at the highest ZIP compression WinRAR can manage. Many of these missing DAT files are indexed from CDNs, and can take up tens of megabytes of uncompressed space.

The remaining storage discrepancy is explained by differences between the standard and parent/clone DAT files. If you take a look at SNES, the standard DAT file has 4,118 titles, whereas the parent/clone has 4,110. It's unclear why the titles are missing from the parent/clone DAT file.
