### ISSUE TITLE
Show Changes Performed During the Run

### ISSUE THREAD

**Issue by PhasecoreX** [emmercm/igir#938]
### Is your feature request related to a problem?

I'd like to be able to see at a glance if Igir actually did what I was expecting it to do. Other (graphical) rom managers show a log of what happened, Igir just has a report of what files it found (existing or new).

### Describe the solution you'd like

Have the stdout show what actions are being performed somehow. Specifically show what files are being copied, moved/renamed, symlinked, or deleted. Perhaps also zipped and extracted as well? You could also have this information present in the report, although the report seems more like a "what files did I find" and not a "what did I do with those files" type of report. If I could get away from generating the report each time, that would be nice.

### Additional context

The report shows what files were found, but there's no way of knowing which of those found ones are new to this run of the command or were already there and untouched (assuming input and output are the same folders). All I really care about is new roms being properly detected and sorted, and knowing which existing ones were deleted. I don't care about the ones that are still there, unchanged. So the report seems overkill for that, and doesn't really give that quick information.

Also, awesome work on this project!

**Comment by emmercm** [comment]
This is somewhat available already by increasing your log verbosity (`-v`, `-vv`, and `-vvv`).

But I've been thinking about this, and I might rework the log levels. Right now they're generally:

- `-v` includes a little bit of extra information, mostly around DATs
- `-vv` includes a little more information
- `-vvv` includes a LOT more information, including every ROM & file being processed, and this mode is mostly for helping generate bug reports

I think it might make more sense to do:

- `-v` includes information about files being processed
- `-vv` includes some additional information such as DAT info
- `-vvv` includes really verbose information, including about ROMs and files that were skipped or weren't found

**Comment by PhasecoreX** [comment]
Yes, I tried doing just the single and double `-v`, but that didn't help. For what it's worth, your proposed verbosity revisions sound great to me! I just would request that the single `-v` would only be file changes, excluding the unchanged files. Not sure if that's what you meant by "information about files being processed".

If someone has a huge collection and is adding one file to it, I think it would be better to just see that one file being added as opposed that one line showing the added file hidden in a sea of "unchanged file" lines. Maybe `-vv` could show unchanged ones as well? Or leave that to the report showing found files.

**Comment by emmercm** [comment]
We're on the same page. I'm thinking:

- `-vv` for files that were copied/moved/symlinked as well as cleaned
- `-vvv` for files that were scanned/processed but had no action taken on them

**Comment by PhasecoreX** [comment]
Thank you, this works great for me with the `-vv` option! One issue though is that if the source and destination directories are the same, `-vv` will also output
```
DEBUG: CandidateWriter: Arcade: dmnfrnt: input and output files are the same, skipping
DEBUG: CandidateWriter: Arcade: dmnfrntpcba: ./test/dmnfrntpcba.zip: not overwriting existing zip file
```
Which I would expect to be in the `-vvv` level, as they are the "no action" ones.

Also of note, `-v` does work for showing the created archives and not showing the no action archives, so that could be my solution, but then I can't see the dry run clean messages on minimum `-vv` level.
