### ISSUE TITLE
Clean Command Dry Run

### ISSUE THREAD

**Issue by PhasecoreX** [emmercm/igir#940]
### Is your feature request related to a problem?

I'd like to know what files Igir intends to delete, but not have it delete them, just list them so I can manually delete them or figure out why they are being deleted.

### Describe the solution you'd like

Add a command line argument for doing a dry run specifically for the `clean` command. Not a global dry run argument, as I still want the file moves/renames/etc. done.

### Additional context

For https://github.com/emmercm/igir/issues/938, it could list them on stdout as an unmatched or unneeded file. Some label that says "this file would have been deleted if it wasn't a dry run". It would only show the files that would have been deleted; not display ones that are in `--clean-exclude` or other UNUSED ones.

**Comment by emmercm** [comment]
I think this is a good suggestion.

Files that are cleaned are recycled (OS and filesystem-dependent, though) in case users want to restore them, but I see the value in this.

**Comment by PhasecoreX** [comment]
On Linux it doesn't seem to actually go to the trash bin, wasn't sure if you wanted yet another feature request from me though haha.

But [trash-cli](https://www.npmjs.com/package/trash-cli) might be able to help with that? The Linux version is [this one](https://github.com/andreafrancia/trash-cli), not sure if the npm one does the same thing.

**Comment by emmercm** [comment]
It looks like `trash-cli` uses the same dependency that `igir` is - [`trash`](https://www.npmjs.com/package/trash), so I suspect this may be a difficult problem to solve across all Linux distros.
