### ISSUE TITLE
Output Hardlink Support

### ISSUE THREAD

**Issue by maxexcloo** [emmercm/igir#942]
### Is your feature request related to a problem?

I use Syncthing to sync ROMs between my handheld device and my NAS. Therefore I maintain a separate output directory that’s synced as it expects EmulationStation format.

### Describe the solution you'd like

Add the ability to link (as opposed to copy or move) files that aren’t changed between input and output and reside on the same disk. Fall back to copy otherwise.

### Additional context

This would greatly lower storage requirements for synced collections 🌟

**Comment by maxexcloo** [comment]
It seems to be supported by Node 🌟

https://nodejs.org/api/fs.html#fspromiseslinkexistingpath-newpath

**Comment by emmercm** [comment]
I _think_ the command you want is `igir symlink`, but I might not have fully understood your suggestion. And it sounds like you might want to mix it as `igir symlink clean`.

Let me know if that works for you, and if not then I probably need some more examples.

**Comment by maxexcloo** [comment]
Symlink sort of works but a symlink is different to a hard link - both are useful and supported by node so maybe both could be supported?

The symlink code would give a good basis of where to implement all the hardlink code so if this is a feature I should have a go at implementing I can give it a shot (testing out my Node knowledge haha)

https://blog.devgenius.io/hard-link-and-a-symbolic-link-any-difference-ef8b9bd61734?gi=0e8eb3ec6dc7

**Comment by maxexcloo** [comment]
On macOS it's possible to convert symlinks to hardlinks using this command, just as a workaround:
`find roms -type l -exec bash -c 'ln -f "$(greadlink -m "$0")" "$0"' {} \;`

Source: https://superuser.com/questions/560597/convert-symlinks-to-hard-links
