### ISSUE TITLE
Duplicate roms reported as UNUSED

### ISSUE THREAD

**Issue by 9p6** [emmercm/igir#982]
### Paste the command

igir report --dat ../dat/Sega\ -\ Mega\ Drive\ -\ Genesis\ \(20240301-041423\).dat --input *.zip

### Describe the bug

As in title it confused me for a bit when analyzing report when first of rom which turned out to be duplicates was reported as FOUND and the other as UNUSED

### Expected behavior

Duplicate roms present in DAT reported with correct status preferably marked as duplicate  

### Debug logs

I feel like they won't be needed here

### igir version

2.5.0

### Node.js version

20.11

### Operating system

Ubuntu

**Comment by emmercm** [comment]
@9p6 can you upload your report so I can analyze it? Feel free to redact any personal directory names.

**Comment by 9p6** [comment]
[igir_2024-03-03T13;33;21.csv](https://github.com/emmercm/igir/files/14472952/igir_2024-03-03T13.33.21.csv)

This is result for a folder with two identical files `Bare Knuckle.zip` and `Streets of Rage.zip`.

**Comment by emmercm** [comment]
`igir` is behaving as expected here according to the rules listed in https://igir.io/output/reporting/, but I see how this could be confusing. I'll consider the suggestion of adding a new report status of `DUPLICATE`.
