### ISSUE TITLE
--prefer-revision-newer or --prefer-revision-older has no impact on ROM selection

### ISSUE THREAD

**Issue by halsafar** [emmercm/igir#987]
### Paste the command

igir -vv link clean \
--symlink \
--input 'ni-roms/roms/Nintendo - Nintendo Entertainment System (Headered)/' \
--dat '.dats/Nintendo - Nintendo Entertainment System (Headered) (20240304-091200).dat' \
--output /nes/roms/igir/ \
--filter-language EN \
--filter-region "USA,WORLD" \
--filter-regex-exclude "GameCube Edition|Virtual Console|e-Reader Edition" \
--no-bios \
--no-device \
--no-bios \
--no-demo \
--no-beta \
--no-sample \
--no-prototype \
--no-test-roms \
--no-aftermarket \
--single \
--prefer-retail \
--prefer-revision-newer

### Describe the bug

Ends up copying two versions of the same game.

### Expected behavior

Should only end up with the latest version of a game.

### Debug logs

```
INFO:  CandidateWriter: Nintendo - Nintendo Entertainment System (Headered): Legend of Zelda, The (USA): creating symlink '/ni-roms/roms/Nintendo - Nintendo Entertainment      System (Headered)/Legend of Zelda, The (USA).zip' -> '/nes/roms/igir/Legend of Zelda, The (USA).zip' 

INFO:  CandidateWriter: Nintendo - Nintendo Entertainment System (Headered): Legend of Zelda, The (USA) (Rev 1): creating symlink '/ni-roms/roms/Nintendo - Nintendo            Entertainment System (Headered)/Legend of Zelda, The (USA) (Rev 1).zip' -> '/nes/roms/igir/Legend of Zelda, The (USA) (Rev 1).zip'
```

### DAT(s) used

Nintendo - Nintendo Entertainment System (Headered) (20240304-091200).dat

### igir version

2.5.0

### Node.js version

N/A

### Operating system

Linux

### Additional context

Same outcome if I use --prefer-revision-older or do not include the argument at all.

**Comment by halsafar** [comment]
If I remove:
```
--filter-language EN \
--filter-region "USA,WORLD" \
```

Then it seems to behave properly and it honors the --prefer-revision settings.

However now I end up with roms from regions I do not want.

**Comment by emmercm** [comment]
Very interesting, I'm surprised no one has reported this bug yet 🙂. The issue is `Legend of Zelda, The (Europe) (Rev 1)` is the "parent" and it was filtered out before preferences were applied - effectively orphaning the children, making them all think they are separate.

This is definitely a serious bug, I'll work on it.

**Comment by halsafar** [comment]
Nice!  Excellent turn around on that one. Thank you so much.   Going to try running from source and test it out.

For years I maintained my own scripts that did similar to what `igir` does but it was all hacky work never meant to be anything I maintained for so long.  I stumbled upon igir a few days ago and I've already replaced years of custom scripts with it. The only thing holding me back from finalizing the transition was this bug.  Thanks again!

**Comment by emmercm** [comment]
Thank you for the kind words @halsafar! I love to hear that my efforts are enjoyed by others.

I just started a [megathread discussion](https://github.com/emmercm/igir/discussions/1000) for people to highlight their use cases, I would love to hear about yours!
